ALTER TABLE "COUNTRIES" MODIFY CONSTRAINT "COUNTRY_REG_FK" DISABLE;
ALTER TABLE "LOCATIONS" MODIFY CONSTRAINT "LOC_C_ID_FK" DISABLE;
ALTER TABLE "EMPLOYEES" MODIFY CONSTRAINT "EMP_JOB_FK" DISABLE;
ALTER TABLE "EMPLOYEES" MODIFY CONSTRAINT "EMP_DEPT_FK" DISABLE;
ALTER TABLE "JOB_HISTORY" MODIFY CONSTRAINT "JHIST_DEPT_FK" DISABLE;
ALTER TABLE "DEPARTMENTS" MODIFY CONSTRAINT "DEPT_LOC_FK" DISABLE;
ALTER TABLE "DEPARTMENTS" MODIFY CONSTRAINT "DEPT_MGR_FK" DISABLE;
ALTER TABLE "EMPLOYEES" MODIFY CONSTRAINT "EMP_MGNR_FK" DISABLE;
ALTER TABLE "JOB_HISTORY" MODIFY CONSTRAINT "JHIST_EMP_FK" DISABLE;
ALTER TABLE "JOB_HISTORY" MODIFY CONSTRAINT "JHIS_JOB_FK" DISABLE;
exit
