LOAD DATA
INFILE 'SCOTT_DM_EMPLOYEE_EVALUATIONS.out'
APPEND INTO TABLE SCOTT.DM_EMPLOYEE_EVALUATIONS
REENABLE
TRAILING NULLCOLS
(
DPSID POSITION(0:8) ,
EE_SEQ POSITION(0:3) ,
EE_TYPE POSITION(0:9) ,
STATUS_CODE POSITION(0:9) ,
FREQUENCY_CODE POSITION(0:4) ,
REMEDIATION_FLAG POSITION(0:0) ,
SPECIAL_EVAL_FLAG POSITION(0:0) ,
COMPLETE_DATE POSITION(0:9) ,
GOALS_MET_FLAG POSITION(0:0) ,
COMPANY_NUMBER POSITION(0:3) ,
JOB_CODE POSITION(0:4) ,
OU_CODE POSITION(0:4) ,
CREATED_BY POSITION(0:39) ,
CREATION_DATE POSITION(0:9) ,
UPDATED_BY POSITION(0:39) ,
LAST_UPDATE_DATE POSITION(0:9) 
)