/INFILES=(pres18.dat, pres19.dat)
	/LENGTH=47
	/FIELD=(field_0, POSITION=23, SIZE=2, EBCDIC)
	/FIELD=(field_1, POSITION=29, SIZE=3, EBCDIC)
	/FIELD=(field_2, POSITION=29, SIZE=1, EBCDIC)
	/FIELD=(field_3, POSITION=34, SIZE=1, EBCDIC)
	/FIELD=(field_4, POSITION=1, SIZE=5, EBCDIC)
	/CONDITION=(cond_0, TEST=(field_2 == field_3 AND field_4 != "Tyler"))
	/OMIT=(CONDITION=cond_0)

/SORT
	/KEY=(field_0, ASCENDING)
	/KEY=(field_1, DESCENDING)
	/STABLE

/OUTFILE=dupl1840
	/LENGTH=47
