/INFILES=(chiefs30.votes)
	/FIELD=(field_0, POSITION=40, SIZE=3, EBCDIC)
	/FIELD=(field_1, POSITION=45, SIZE=2, EBCDIC)
	/FIELD=(field_2, POSITION=23, SIZE=3, EBCDIC)
	/CONDITION=(cond_0, TEST=(field_0 OR field_1))

/SORT
	/KEY=(field_0, ASCENDING)
	/KEY=(field_1, ASCENDING)

/OUTFILE=termsums
	/FIELD=(field_2_sum, POSITION=23, SIZE=3, EBCDIC)
	/SUM field_2_sum FROM field_2 BREAK cond_0
