LOAD DATA
INFILE 'C:/IRI/CoSort95/workbench/workspace/RowGen_Test_DB_Data/DFdemo/DM_EMPLOYEES.out'
APPEND INTO TABLE DM_EMPLOYEES
REENABLE
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(
DPSID NULLIF(DPSID="{NULL}") ,
EMPLOYEE_ID NULLIF(EMPLOYEE_ID="{NULL}") ,
STATUS_CODE NULLIF(STATUS_CODE="{NULL}") ,
END_DATE NULLIF(END_DATE="{NULL}")  "to_date(:END_DATE, 'YYYY-MM-DD')",
HIRE_DATE NULLIF(HIRE_DATE="{NULL}")  "to_date(:HIRE_DATE, 'YYYY-MM-DD')",
SUPERVISOR_DPSID NULLIF(SUPERVISOR_DPSID="{NULL}") ,
MANAGER_DPSID NULLIF(MANAGER_DPSID="{NULL}") ,
OPT_IN_DATE NULLIF(OPT_IN_DATE="{NULL}")  "to_date(:OPT_IN_DATE, 'YYYY-MM-DD')",
DOB NULLIF(DOB="{NULL}")  "to_date(:DOB, 'YYYY-MM-DD')",
GENDER NULLIF(GENDER="{NULL}") ,
LAST_NAME NULLIF(LAST_NAME="{NULL}") ,
FIRST_NAME NULLIF(FIRST_NAME="{NULL}") ,
MIDDLE_NAME NULLIF(MIDDLE_NAME="{NULL}") ,
GENERATION NULLIF(GENERATION="{NULL}") ,
SSN NULLIF(SSN="{NULL}") ,
ETHNIC_CODE NULLIF(ETHNIC_CODE="{NULL}") ,
EMAIL_ADDRESS NULLIF(EMAIL_ADDRESS="{NULL}") ,
ADDRESS_ID NULLIF(ADDRESS_ID="{NULL}") ,
USER_STAMP NULLIF(USER_STAMP="{NULL}") ,
DATE_STAMP NULLIF(DATE_STAMP="{NULL}")  "to_date(:DATE_STAMP, 'YYYY-MM-DD')",
TIME_STAMP NULLIF(TIME_STAMP="{NULL}") ,
CREATED_BY NULLIF(CREATED_BY="{NULL}") ,
CREATION_DATE NULLIF(CREATION_DATE="{NULL}")  "to_date(:CREATION_DATE, 'YYYY-MM-DD')",
UPDATED_BY NULLIF(UPDATED_BY="{NULL}") ,
LAST_UPDATE_DATE NULLIF(LAST_UPDATE_DATE="{NULL}")  "to_date(:LAST_UPDATE_DATE, 'YYYY-MM-DD')"
)