DROP TABLE ORDERS_NF;

CREATE TABLE ORDERS_NF (
		ORDER_ID VARCHAR(5) NOT NULL,
		CUSTOMER_ID NUMERIC(5) NOT NULL,
		FREIGHT NUMERIC(5, 0),
		TOTAL NUMERIC(10, 2)
	);

CREATE UNIQUE INDEX ORDER_ID_PK ON ORDERS_NF (ORDER_ID ASC);

ALTER TABLE ORDERS_NF ADD CONSTRAINT ORDER_ID_PK PRIMARY KEY (ORDER_ID);
