DROP TABLE COMPANIES_TEST;
 
CREATE TABLE COMPANIES_TEST (
			COMPANY_NUMBER NUMERIC(19,0),
			COMPANY_NAME VARCHAR(50)
			);
ALTER TABLE COMPANIES_TEST ADD PRIMARY KEY (COMPANY_NUMBER );

/*
CREATE TABLE COMPANIES_TEST (
			COMPANY_NUMBER NUMERIC(4,0),
			COMPANY_NAME VARCHAR(40)
			);
ALTER TABLE COMPANIES_TEST ADD PRIMARY KEY (COMPANY_NUMBER);
*/
