ALTER TABLE CLIENT DROP PRIMARY KEY;

DROP TABLE CLIENT;

CREATE TABLE CLIENT (
	ID DECIMAL(10,0),
	LAST_NAME VARCHAR(30),
	FIRST_NAME VARCHAR(30),
	MIDDLE_NAME VARCHAR(30),
	STREET VARCHAR(50),
	CITY VARCHAR(30),
	STATE VARCHAR(2),
	ZIP DECIMAL(10,0),
	PHONE DECIMAL(10,0),
	EMAIL VARCHAR(40),
	SSN VARCHAR(11),
	CREATED TIMESTAMP,
	UPDATED TIMESTAMP
) ENGINE=InnoDB;

ALTER TABLE CLIENT ADD CONSTRAINT CLIENT_PK PRIMARY KEY (ID);
