LOAD DATA
INFILE 'C:/IRI/workspace-demos/Flow/setup/ORDERS.out'
APPEND INTO TABLE ORDERS_FLOW
REENABLE
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(
ORDER_ID NULLIF(ORDER_ID="{NULL}") ,
CUSTOMER_ID NULLIF(CUSTOMER_ID="{NULL}") ,
FREIGHT NULLIF(FREIGHT="{NULL}") ,
TOTAL NULLIF(TOTAL="{NULL}") 
)