LOAD DATA
INFILE 'SCOTT_DM_ORGANIZATIONAL_UNITS.out'
APPEND INTO TABLE SCOTT.DM_ORGANIZATIONAL_UNITS
REENABLE
TRAILING NULLCOLS
(
COMPANY_NUMBER POSITION(0:3) ,
OU_CODE POSITION(0:4) ,
DESCRIPTION POSITION(0:3999) ,
CREATED_BY POSITION(0:39) ,
CREATION_DATE POSITION(0:9) ,
UPDATED_BY POSITION(0:39) ,
LAST_UPDATE_DATE POSITION(0:9) 
)