CREATE TABLE PERSONS (
		SSN VARCHAR2(11) NOT NULL,
		LASTNAME VARCHAR2(50) NOT NULL,
		FIRSTNAME VARCHAR2(50),
		ADDRESS VARCHAR2(50),
		CITY VARCHAR2(50),
		STATE VARCHAR2(2),
		ZIP VARCHAR2(5),
		CREDIT_CARD VARCHAR2(19)
	);

ALTER TABLE PERSONS ADD CONSTRAINT SSN_PK PRIMARY KEY (SSN);

--DROP TABLE PERSONS;

-- SELECT count(*) FROM PERSONS;
