# @echo off
sortcl /SPECIFICATION=SCOTT_CUSTOMERS_REP.scl
sortcl /SPECIFICATION=SCOTT_EMPLOYEES.scl
sortcl /SPECIFICATION=SCOTT_JOB_HISTORY.scl
sortcl /SPECIFICATION=SCOTT_PATIENT_RECORD.scl
sortcl /SPECIFICATION=SCOTT_PERSONS.scl