CREATE TABLE PERSONS (
		SSN NUMBER(9, 0) NOT NULL,
		LASTNAME VARCHAR2(50) NOT NULL,
		FIRSTNAME VARCHAR2(50),
		ADDRESS VARCHAR2(50),
		CITY VARCHAR2(50),
		STATE VARCHAR2(2),
		ZIP VARCHAR2(5)
	);

ALTER TABLE PERSONS ADD CONSTRAINT SSN_PK PRIMARY KEY (SSN);

