LOAD DATA
INFILE 'C:/IRI/CoSort95/workbench/workspace/RowGen_Test_DB_Data/DFdemo/DM_EMPLOYEE_EVALUATIONS.out'
APPEND INTO TABLE DM_EMPLOYEE_EVALUATIONS
REENABLE
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(
DPSID NULLIF(DPSID="{NULL}") ,
EE_SEQ NULLIF(EE_SEQ="{NULL}") ,
EE_TYPE NULLIF(EE_TYPE="{NULL}") ,
STATUS_CODE NULLIF(STATUS_CODE="{NULL}") ,
FREQUENCY_CODE NULLIF(FREQUENCY_CODE="{NULL}") ,
REMEDIATION_FLAG NULLIF(REMEDIATION_FLAG="{NULL}") ,
SPECIAL_EVAL_FLAG NULLIF(SPECIAL_EVAL_FLAG="{NULL}") ,
COMPLETE_DATE NULLIF(COMPLETE_DATE="{NULL}")  "to_date(:COMPLETE_DATE, 'YYYY-MM-DD')",
GOALS_MET_FLAG NULLIF(GOALS_MET_FLAG="{NULL}") ,
COMPANY_NUMBER NULLIF(COMPANY_NUMBER="{NULL}") ,
JOB_CODE NULLIF(JOB_CODE="{NULL}") ,
OU_CODE NULLIF(OU_CODE="{NULL}") ,
CREATED_BY NULLIF(CREATED_BY="{NULL}") ,
CREATION_DATE NULLIF(CREATION_DATE="{NULL}")  "to_date(:CREATION_DATE, 'YYYY-MM-DD')",
UPDATED_BY NULLIF(UPDATED_BY="{NULL}") ,
LAST_UPDATE_DATE NULLIF(LAST_UPDATE_DATE="{NULL}")  "to_date(:LAST_UPDATE_DATE, 'YYYY-MM-DD')"
)