ALTER TABLE SCOTT.DEPARTMENTS DISABLE CONSTRAINT D_L_ID_FK;
ALTER TABLE SCOTT.EMPLOYEES DISABLE CONSTRAINT E_J_ID_FK;
ALTER TABLE SCOTT.JOB_HISTORY DISABLE CONSTRAINT JH_J_ID_FK;
ALTER TABLE SCOTT.EMPLOYEES DISABLE CONSTRAINT E_D_ID_FK;
ALTER TABLE SCOTT.JOB_HISTORY DISABLE CONSTRAINT JH_D_ID_FK;
exit
