ALTER TABLE "EMPLOYEES" MODIFY CONSTRAINT "EMP_DEPT_FK" DISABLE;
ALTER TABLE "JOB_HISTORY" MODIFY CONSTRAINT "JHIST_DEPT_FK" DISABLE;
ALTER TABLE "DEPARTMENTS" MODIFY CONSTRAINT "DEPT_MGR_FK" DISABLE;
ALTER TABLE "EMPLOYEES" MODIFY CONSTRAINT "EMP_MGNR_FK" DISABLE;
ALTER TABLE "JOB_HISTORY" MODIFY CONSTRAINT "JHIST_EMP_FK" DISABLE;
exit
