ALTER TABLE DEPARTMENTS DISABLE CONSTRAINT DEPT_MGR_FK;
ALTER TABLE EMPLOYEES DISABLE CONSTRAINT EMP_DEPT_FK;
ALTER TABLE EMPLOYEES DISABLE CONSTRAINT EMP_MGNR_FK;
ALTER TABLE JOB_HISTORY DISABLE CONSTRAINT JHIST_DEPT_FK;
ALTER TABLE JOB_HISTORY DISABLE CONSTRAINT JHIST_EMP_FK;
exit
