ALTER TABLE "EMPLOYEES" MODIFY CONSTRAINT "EMP_DEPT_FK" ENABLE;
ALTER TABLE "JOB_HISTORY" MODIFY CONSTRAINT "JHIST_DEPT_FK" ENABLE;
ALTER TABLE "DEPARTMENTS" MODIFY CONSTRAINT "DEPT_MGR_FK" ENABLE;
ALTER TABLE "EMPLOYEES" MODIFY CONSTRAINT "EMP_MGNR_FK" ENABLE;
ALTER TABLE "JOB_HISTORY" MODIFY CONSTRAINT "JHIST_EMP_FK" ENABLE;
exit
