ALTER TABLE SCOTT.DEPARTMENTS ENABLE CONSTRAINT D_L_ID_FK;
ALTER TABLE SCOTT.EMPLOYEES ENABLE CONSTRAINT E_J_ID_FK;
ALTER TABLE SCOTT.JOB_HISTORY ENABLE CONSTRAINT JH_J_ID_FK;
ALTER TABLE SCOTT.EMPLOYEES ENABLE CONSTRAINT E_D_ID_FK;
ALTER TABLE SCOTT.JOB_HISTORY ENABLE CONSTRAINT JH_D_ID_FK;
exit
