ALTER TABLE DEPARTMENTS ENABLE CONSTRAINT DEPT_MGR_FK;
ALTER TABLE EMPLOYEES ENABLE CONSTRAINT EMP_DEPT_FK;
ALTER TABLE EMPLOYEES ENABLE CONSTRAINT EMP_MGNR_FK;
ALTER TABLE JOB_HISTORY ENABLE CONSTRAINT JHIST_DEPT_FK;
ALTER TABLE JOB_HISTORY ENABLE CONSTRAINT JHIST_EMP_FK;
exit
