ALTER TABLE "DM_DCTA_EVALUATIONS" MODIFY CONSTRAINT "DM_EE_DCTAE_FK" DISABLE;
ALTER TABLE "DM_EMPLOYEES" MODIFY CONSTRAINT "DM_EMP_MGR_FK" DISABLE;
ALTER TABLE "DM_EMPLOYEES" MODIFY CONSTRAINT "DM_EMP_EMP_FK" DISABLE;
ALTER TABLE "DM_EMPLOYEE_EVALUATIONS" MODIFY CONSTRAINT "DM_EE_EMP_FK" DISABLE;
ALTER TABLE "DM_EMPLOYEE_EVALUATIONS" MODIFY CONSTRAINT "DM_EE_JT_FK" DISABLE;
ALTER TABLE "DM_EMPLOYEE_EVALUATIONS" MODIFY CONSTRAINT "DM_EE_OU_FK" DISABLE;
ALTER TABLE "DM_JOB_TYPES" MODIFY CONSTRAINT "DM_JT_COMPANIES_FK" DISABLE;
ALTER TABLE "DM_JOB_TYPES" MODIFY CONSTRAINT "DM_JT_FK_PARENT_TOP" DISABLE;
ALTER TABLE "DM_JOB_TYPES" MODIFY CONSTRAINT "DM_JT_FK_PARENT" DISABLE;
ALTER TABLE "DM_ORGANIZATIONAL_UNITS" MODIFY CONSTRAINT "DM_OU_COMPANIES_FK" DISABLE;
exit
