LOAD DATA
INFILE 'SCOTT_DM_DCTA_EVALUATIONS.out'
APPEND INTO TABLE SCOTT.DM_DCTA_EVALUATIONS
REENABLE
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(
DPSID NULLIF(DPSID="{NULL}") ,
EE_SEQ NULLIF(EE_SEQ="{NULL}") ,
DCTAE_TYPE NULLIF(DCTAE_TYPE="{NULL}") ,
PLAN_CODE NULLIF(PLAN_CODE="{NULL}") ,
SEMESTER_DUE NULLIF(SEMESTER_DUE="{NULL}") ,
YEAR_DUE NULLIF(YEAR_DUE="{NULL}") ,
JOB_FTE_CODE NULLIF(JOB_FTE_CODE="{NULL}") ,
SRC_USER_ID NULLIF(SRC_USER_ID="{NULL}") ,
SRC_UPDATE_DATE NULLIF(SRC_UPDATE_DATE="{NULL}")  "to_date(:SRC_UPDATE_DATE, 'YYYY-MM-DD')"
)