LOAD DATA
INFILE 'SCOTT_DM_ORGANIZATIONAL_UNITS.out'
APPEND INTO TABLE SCOTT.DM_ORGANIZATIONAL_UNITS
REENABLE
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(
COMPANY_NUMBER NULLIF(COMPANY_NUMBER="{NULL}") ,
OU_CODE NULLIF(OU_CODE="{NULL}") ,
DESCRIPTION CHAR(4000) NULLIF(DESCRIPTION="{NULL}") ,
CREATED_BY NULLIF(CREATED_BY="{NULL}") ,
CREATION_DATE NULLIF(CREATION_DATE="{NULL}")  "to_date(:CREATION_DATE, 'YYYY-MM-DD')",
UPDATED_BY NULLIF(UPDATED_BY="{NULL}") ,
LAST_UPDATE_DATE NULLIF(LAST_UPDATE_DATE="{NULL}")  "to_date(:LAST_UPDATE_DATE, 'YYYY-MM-DD')"
)