LOAD DATA
INFILE 'SCOTT_DM_JOB_TYPES.out'
APPEND INTO TABLE SCOTT.DM_JOB_TYPES
REENABLE
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(
COMPANY_NUMBER NULLIF(COMPANY_NUMBER="{NULL}") ,
JOB_CODE NULLIF(JOB_CODE="{NULL}") ,
DESCRIPTION CHAR(4000) NULLIF(DESCRIPTION="{NULL}") ,
JOB_CLASS_CODE NULLIF(JOB_CLASS_CODE="{NULL}") ,
BIGGER_JOB_COMPANY NULLIF(BIGGER_JOB_COMPANY="{NULL}") ,
BIGGER_JOB_CODE NULLIF(BIGGER_JOB_CODE="{NULL}") ,
SUPER_JOB_COMPANY NULLIF(SUPER_JOB_COMPANY="{NULL}") ,
SUPER_JOB_CODE NULLIF(SUPER_JOB_CODE="{NULL}") ,
CREATED_BY NULLIF(CREATED_BY="{NULL}") ,
CREATION_DATE NULLIF(CREATION_DATE="{NULL}")  "to_date(:CREATION_DATE, 'YYYY-MM-DD')",
UPDATED_BY NULLIF(UPDATED_BY="{NULL}") ,
LAST_UPDATE_DATE NULLIF(LAST_UPDATE_DATE="{NULL}")  "to_date(:LAST_UPDATE_DATE, 'YYYY-MM-DD')"
)