DROP TABLE CUSTOMERS_NF;

CREATE TABLE CUSTOMERS_NF (
		ID NUMERIC(5, 0) NOT NULL,
		NAME VARCHAR(20) NOT NULL,
		ADDRESS VARCHAR(25),
		PHONE VARCHAR(10)
	);

CREATE UNIQUE INDEX ID_PK ON CUSTOMERS_NF (ID ASC);
ALTER TABLE CUSTOMERS_NF ADD CONSTRAINT ID_PK PRIMARY KEY (ID);


