ALTER TABLE SCOTT.SUB_SALE_DIM ENABLE CONSTRAINT SUB_SALE_DIM_FK1;
ALTER TABLE SCOTT.SUB_SALE_DIM ENABLE CONSTRAINT SUB_SALE_DIM_FK2;
ALTER TABLE SCOTT.SUB_SALE_DIM ENABLE CONSTRAINT SUB_SALE_DIM_FK3;
ALTER TABLE SCOTT.SUB_SALE_DIM ENABLE CONSTRAINT SUB_SALE_DIM_FK4;
ALTER TABLE SCOTT.SUB_SALE_DIM ENABLE CONSTRAINT SUB_SALE_DIM_FK5;
ALTER TABLE SCOTT.SUB_SALE_DIM ENABLE CONSTRAINT SUB_SALE_DIM_FK6;
ALTER TABLE SCOTT.SUB_SALE_DIM ENABLE CONSTRAINT SUB_SALE_DIM_FK7;
exit
