ALTER TABLE DV_EMPLOYEES_HR DROP CONSTRAINT DV_EMP_JOB_HR_FK;

ALTER TABLE DV_DEPARTMENTS_HR DROP CONSTRAINT DV_DEPT_LOC_HR_FK;

ALTER TABLE DV_EMPLOYEES_HR DROP CONSTRAINT DV_EMP_MANAGER_HR_FK;

ALTER TABLE DV_JOB_HISTORY_HR DROP CONSTRAINT DV_JHIST_DEPT_HR_FK;

ALTER TABLE DV_COUNTRIES_HR DROP CONSTRAINT DV_COUNTR_REG_HR_FK;

ALTER TABLE DV_JOB_HISTORY_HR DROP CONSTRAINT DV_JHIST_EMP_HR_FK;

ALTER TABLE DV_JOB_HISTORY_HR DROP CONSTRAINT DV_JHIST_JOB_HR_FK;

ALTER TABLE DV_LOCATIONS_HR DROP CONSTRAINT DV_LOC_C_ID_HR_FK;

ALTER TABLE DV_EMPLOYEES_HR DROP CONSTRAINT DV_EMP_DEPT_HR_FK;

ALTER TABLE DV_DEPARTMENTS_HR DROP CONSTRAINT DV_DEPT_ID_HR_PK;

ALTER TABLE DV_JOB_HISTORY_HR DROP CONSTRAINT DV_JHIST_EMP_ID_ST_DATE_HR_PK;

ALTER TABLE DV_EMPLOYEES_HR DROP CONSTRAINT DV_EMP_EMP_ID_HR_PK;

ALTER TABLE DV_COUNTRIES_HR DROP CONSTRAINT DV_COUNTRY_C_ID_HR_PK;

ALTER TABLE DV_LOCATIONS_HR DROP CONSTRAINT DV_LOC_ID_HR_PK;

ALTER TABLE DV_JOBS_HR DROP CONSTRAINT DV_JOB_ID_HR_PK;

ALTER TABLE DV_REGIONS_HR DROP CONSTRAINT DV_REG_ID_HR_PK;

DROP INDEX DV_EMP_EMP_ID_HR_PK;

DROP INDEX DV_EMP_NAME_HR_IX;

DROP INDEX DV_LOC_COUNTRY_HR_IX;

DROP INDEX DV_JHIST_EMPLOYEE_HR_IX;

DROP INDEX DV_EMP_MANAGER_HR_IX;

DROP INDEX DV_JHIST_JOB_HR_IX;

DROP INDEX DV_EMP_DEPARTMENT_HR_IX;

DROP INDEX DV_JOB_ID_HR_PK;

DROP INDEX DV_EMP_JOB_HR_IX;

DROP INDEX DV_JHIST_DEPARTMENT_HR_IX;

DROP INDEX DV_JHIST_EMP_ID_ST_DATE_HR_PK;

DROP INDEX DV_DEPT_LOCATION_HR_IX;

DROP INDEX DV_LOC_ID_HR_PK;

DROP INDEX DV_EMP_EMAIL_HR_UK;

DROP INDEX DV_COUNTRY_C_ID_HR_PK;

DROP INDEX DV_LOC_CITY_HR_IX;

DROP INDEX DV_DEPT_ID_HR_PK;

DROP INDEX DV_REG_ID_HR_PK;

DROP INDEX DV_LOC_STATE_PROVINCE_HR_IX;

DROP TABLE DV_JOB_HISTORY_HR;

DROP TABLE DV_LOCATIONS_HR;

DROP TABLE DV_DEPARTMENTS_HR;

DROP TABLE DV_COUNTRIES_HR;

DROP TABLE DV_JOBS_HR;

DROP TABLE DV_EMPLOYEES_HR;

DROP TABLE DV_REGIONS_HR;

CREATE TABLE DV_JOB_HISTORY_HR (
		EMPLOYEE_ID NUMBER(6 , 0) NOT NULL,
		START_DATE DATE NOT NULL,
		END_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE TABLE DV_LOCATIONS_HR (
		LOCATION_ID NUMBER(4 , 0) NOT NULL,
		STREET_ADDRESS VARCHAR2(40),
		POSTAL_CODE VARCHAR2(12),
		CITY VARCHAR2(30) NOT NULL,
		STATE_PROVINCE VARCHAR2(25),
		COUNTRY_ID CHAR(2)
	);

CREATE TABLE DV_DEPARTMENTS_HR (
		DEPARTMENT_ID NUMBER(4 , 0) NOT NULL,
		DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
		LOCATION_ID NUMBER(4 , 0)
	);

CREATE TABLE DV_COUNTRIES_HR (
		COUNTRY_ID CHAR(2) NOT NULL,
		COUNTRY_NAME VARCHAR2(40),
		REGION_ID NUMBER(38 , 0)
	);

CREATE TABLE DV_JOBS_HR (
		JOB_ID VARCHAR2(10) NOT NULL,
		JOB_TITLE VARCHAR2(35) NOT NULL,
		MIN_SALARY NUMBER(6 , 0),
		MAX_SALARY NUMBER(6 , 0)
	);

CREATE TABLE DV_EMPLOYEES_HR (
		EMPLOYEE_ID NUMBER(6 , 0) NOT NULL,
		FIRST_NAME VARCHAR2(20),
		LAST_NAME VARCHAR2(25) NOT NULL,
		EMAIL VARCHAR2(25) NOT NULL,
		PHONE_NUMBER VARCHAR2(20),
		HIRE_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		SALARY NUMBER(8 , 2),
		COMMISSION_PCT NUMBER(2 , 2),
		MANAGER_ID NUMBER(6 , 0),
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE TABLE DV_REGIONS_HR (
		REGION_ID NUMBER(38 , 0) NOT NULL,
		REGION_NAME VARCHAR2(25)
	);

CREATE UNIQUE INDEX DV_EMP_EMP_ID_HR_PK ON DV_EMPLOYEES_HR (EMPLOYEE_ID ASC);

CREATE INDEX DV_EMP_NAME_HR_IX ON DV_EMPLOYEES_HR (LAST_NAME ASC, FIRST_NAME ASC);

CREATE INDEX DV_LOC_COUNTRY_HR_IX ON DV_LOCATIONS_HR (COUNTRY_ID ASC);

CREATE INDEX DV_JHIST_EMPLOYEE_HR_IX ON DV_JOB_HISTORY_HR (EMPLOYEE_ID ASC);

CREATE INDEX DV_EMP_MANAGER_HR_IX ON DV_EMPLOYEES_HR (MANAGER_ID ASC);

CREATE INDEX DV_JHIST_JOB_HR_IX ON DV_JOB_HISTORY_HR (JOB_ID ASC);

CREATE INDEX DV_EMP_DEPARTMENT_HR_IX ON DV_EMPLOYEES_HR (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX DV_JOB_ID_HR_PK ON DV_JOBS_HR (JOB_ID ASC);

CREATE INDEX DV_EMP_JOB_HR_IX ON DV_EMPLOYEES_HR (JOB_ID ASC);

CREATE INDEX DV_JHIST_DEPARTMENT_HR_IX ON DV_JOB_HISTORY_HR (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX DV_JHIST_EMP_ID_ST_DATE_HR_PK ON DV_JOB_HISTORY_HR (EMPLOYEE_ID ASC, START_DATE ASC);

CREATE INDEX DV_DEPT_LOCATION_HR_IX ON DV_DEPARTMENTS_HR (LOCATION_ID ASC);

CREATE UNIQUE INDEX DV_LOC_ID_HR_PK ON DV_LOCATIONS_HR (LOCATION_ID ASC);

CREATE UNIQUE INDEX DV_EMP_EMAIL_HR_UK ON DV_EMPLOYEES_HR (EMAIL ASC);

CREATE UNIQUE INDEX DV_COUNTRY_C_ID_HR_PK ON DV_COUNTRIES_HR (COUNTRY_ID ASC);

CREATE INDEX DV_LOC_CITY_HR_IX ON DV_LOCATIONS_HR (CITY ASC);

CREATE UNIQUE INDEX DV_DEPT_ID_HR_PK ON DV_DEPARTMENTS_HR (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX DV_REG_ID_HR_PK ON DV_REGIONS_HR (REGION_ID ASC);

CREATE INDEX DV_LOC_STATE_PROVINCE_HR_IX ON DV_LOCATIONS_HR (STATE_PROVINCE ASC);

ALTER TABLE DV_DEPARTMENTS_HR ADD CONSTRAINT DV_DEPT_ID_HR_PK PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE DV_JOB_HISTORY_HR ADD CONSTRAINT DV_JHIST_EMP_ID_ST_DATE_HR_PK PRIMARY KEY (EMPLOYEE_ID, START_DATE);

ALTER TABLE DV_EMPLOYEES_HR ADD CONSTRAINT DV_EMP_EMP_ID_HR_PK PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE DV_COUNTRIES_HR ADD CONSTRAINT DV_COUNTRY_C_ID_HR_PK PRIMARY KEY (COUNTRY_ID);

ALTER TABLE DV_LOCATIONS_HR ADD CONSTRAINT DV_LOC_ID_HR_PK PRIMARY KEY (LOCATION_ID);

ALTER TABLE DV_JOBS_HR ADD CONSTRAINT DV_JOB_ID_HR_PK PRIMARY KEY (JOB_ID);

ALTER TABLE DV_REGIONS_HR ADD CONSTRAINT DV_REG_ID_HR_PK PRIMARY KEY (REGION_ID);

ALTER TABLE DV_EMPLOYEES_HR ADD CONSTRAINT DV_EMP_JOB_HR_FK FOREIGN KEY (JOB_ID)
	REFERENCES DV_JOBS_HR (JOB_ID);

ALTER TABLE DV_DEPARTMENTS_HR ADD CONSTRAINT DV_DEPT_LOC_HR_FK FOREIGN KEY (LOCATION_ID)
	REFERENCES DV_LOCATIONS_HR (LOCATION_ID);

ALTER TABLE DV_EMPLOYEES_HR ADD CONSTRAINT DV_EMP_MANAGER_HR_FK FOREIGN KEY (MANAGER_ID)
	REFERENCES DV_EMPLOYEES_HR (EMPLOYEE_ID);

ALTER TABLE DV_JOB_HISTORY_HR ADD CONSTRAINT DV_JHIST_DEPT_HR_FK FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DV_DEPARTMENTS_HR (DEPARTMENT_ID);

ALTER TABLE DV_COUNTRIES_HR ADD CONSTRAINT DV_COUNTR_REG_HR_FK FOREIGN KEY (REGION_ID)
	REFERENCES DV_REGIONS_HR (REGION_ID);

ALTER TABLE DV_JOB_HISTORY_HR ADD CONSTRAINT DV_JHIST_EMP_HR_FK FOREIGN KEY (EMPLOYEE_ID)
	REFERENCES DV_EMPLOYEES_HR (EMPLOYEE_ID);

ALTER TABLE DV_JOB_HISTORY_HR ADD CONSTRAINT DV_JHIST_JOB_HR_FK FOREIGN KEY (JOB_ID)
	REFERENCES DV_JOBS_HR (JOB_ID);

ALTER TABLE DV_LOCATIONS_HR ADD CONSTRAINT DV_LOC_C_ID_HR_FK FOREIGN KEY (COUNTRY_ID)
	REFERENCES DV_COUNTRIES_HR (COUNTRY_ID);

ALTER TABLE DV_EMPLOYEES_HR ADD CONSTRAINT DV_EMP_DEPT_HR_FK FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DV_DEPARTMENTS_HR (DEPARTMENT_ID);

