--ScriptOptions statementTerminator=;

CREATE TABLE ORDERS (	
	ORDER_ID VARCHAR2(5),		
	CUSTOMER VARCHAR2(200),		
	EMPLOYEE VARCHAR2(200),		
	SHIP_DATE TIMESTAMP,		
	FREIGHT NUMBER(22 , 0)	
);
