--<ScriptOptions statementTerminator=";"/>

ALTER TABLE COUNTRIES DROP CONSTRAINT COUNTRY_REG_FK;

ALTER TABLE DM_JOB_TYPES DROP CONSTRAINT DM_JT_FK_PARENT_TOP;

ALTER TABLE DM_JOB_TYPES DROP CONSTRAINT DM_JT_COMPANIES_FK;

ALTER TABLE DM_DCTA_EVALUATIONS DROP CONSTRAINT DM_EE_DCTAE_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JHIS_JOB_FK;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DROP CONSTRAINT DM_EE_JT_FK;

ALTER TABLE LOCATIONS DROP CONSTRAINT LOC_C_ID_FK;

ALTER TABLE DM_EMPLOYEES DROP CONSTRAINT DM_EMP_EMP_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_MGNR_FK;

ALTER TABLE DM_ORGANIZATIONAL_UNITS DROP CONSTRAINT DM_OU_COMPANIES_FK;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DROP CONSTRAINT DM_EE_EMP_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_JOB_FK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT DEPT_LOC_FK;

ALTER TABLE ORDERS_FLOW DROP CONSTRAINT CUSTOMERS_FK;

ALTER TABLE DM_EMPLOYEES DROP CONSTRAINT DM_EMP_MGR_FK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT DEPT_MGR_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JHIST_EMP_FK;

ALTER TABLE DM_JOB_TYPES DROP CONSTRAINT DM_JT_FK_PARENT;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DROP CONSTRAINT DM_EE_OU_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JHIST_DEPT_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_DEPT_FK;

ALTER TABLE DM_COMPANIES DROP CONSTRAINT DM_COMPANIES_PK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_EMP_ID_PK;

ALTER TABLE DM_ORGANIZATIONAL_UNITS DROP CONSTRAINT DM_OU_PK;

ALTER TABLE PERSONS DROP CONSTRAINT SSN_PK;

ALTER TABLE ORDERS_FLOW DROP CONSTRAINT ORDERS_PK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT DEPT_ID_PK;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DROP CONSTRAINT DM_EE_PK;

ALTER TABLE COMPANIES_TEST DROP CONSTRAINT SYS_C0011557;

ALTER TABLE JOBS DROP CONSTRAINT JOB_ID_PK;

ALTER TABLE REGIONS DROP CONSTRAINT REG_ID_PK;

ALTER TABLE DM_JOB_TYPES DROP CONSTRAINT DM_JT_PK;

ALTER TABLE COUNTRIES DROP CONSTRAINT COUNTRY_C_ID_PK;

ALTER TABLE CUSTOMERS_FLOW DROP CONSTRAINT CUSTOMERS_PK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JHIST_EMP_ID_ST_DATE_PK;

ALTER TABLE CUSTOMERS_SAMPLES DROP CONSTRAINT CUSTOMERS_SAMPLES_PK;

ALTER TABLE LOCATIONS DROP CONSTRAINT LOC_ID_PK;

ALTER TABLE DM_EMPLOYEES DROP CONSTRAINT DM_EMP_PK;

ALTER TABLE DM_DCTA_EVALUATIONS DROP CONSTRAINT DM_DCTAE_PK;

ALTER TABLE CUSTOMERS_REP DROP CONSTRAINT CUSTOMERS_REP_SSN_PK;

DROP INDEX SSN_PK;

DROP INDEX DM_COMPANIES_PK;

DROP INDEX EMP_NAME_IX;

DROP INDEX SYS_C0011557;

DROP INDEX EMP_JOB_IX;

DROP INDEX ORDERS_PK;

DROP INDEX LOC_CITY_IX;

DROP INDEX JHIST_EMP_ID_ST_DATE_PK;

DROP INDEX CUSTOMERS_PK;

DROP INDEX DM_JT_PK;

DROP INDEX DM_EMP_UK;

DROP INDEX DM_OU_PK;

DROP INDEX JOB_ID_PK;

DROP INDEX LOC_STATE_PROVINCE_IX;

DROP INDEX COUNTRY_C_ID_PK;

DROP INDEX REG_ID_PK;

DROP INDEX LOC_COUNTRY_IX;

DROP INDEX DEPT_ID_PK;

DROP INDEX EMP_EMAIL_UK;

DROP INDEX CUSTOMERS_SAMPLES_PK;

DROP INDEX DEPT_LOCATION_IX;

DROP INDEX DM_EMP_UK2;

DROP INDEX EMP_MANAGER_IX;

DROP INDEX EMP_DEPARTMENT_IX;

DROP INDEX DM_EMP_PK;

DROP INDEX JHIST_DEPARTMENT_IX;

DROP INDEX EMP_EMP_ID_PK;

DROP INDEX DM_EE_PK;

DROP INDEX JHIST_JOB_IX;

DROP INDEX JHIST_EMPLOYEE_IX;

DROP INDEX CUSTOMERS_REP_SSN_PK;

DROP INDEX LOC_ID_PK;

DROP INDEX DM_DCTAE_PK;

DROP TABLE CUSTOMERS_FLOW;

DROP TABLE CUSTOMER_TRANS7;

DROP TABLE DM_DCTA_EVALUATIONS;

DROP TABLE DM_ORGANIZATIONAL_UNITS;

DROP TABLE PATIENT_RECORD;

DROP TABLE ORDERS;

DROP TABLE PATIENT_RECORD_ENCRYPTED;

DROP TABLE CUSTOMERS_REP;

DROP TABLE DM_JOB_TYPES;

DROP TABLE CUSTOMER_TRANS;

DROP TABLE REGIONS;

DROP TABLE COUNTRIES;

DROP TABLE DEMO2;

DROP TABLE DEPARTMENTS;

DROP TABLE COMPANIES_TEST;

DROP TABLE XL4;

DROP TABLE PERSONS;

DROP TABLE DEMO_ROWGEN;

DROP TABLE DM_EMPLOYEES;

DROP TABLE JOBS;

DROP TABLE EMPLOYEES;

DROP TABLE JOB_HISTORY;

DROP TABLE DM_EMPLOYEE_EVALUATIONS;

DROP TABLE ORDERS_FLOW;

DROP TABLE CUSTOMERS_SAMPLES;

DROP TABLE DM_COMPANIES;

DROP TABLE YEAR_DEPT_AMT;

DROP TABLE LOCATIONS;

DROP TABLE DEMO_COMPANIES;

DROP TABLE ORDERS_SORTED;

CREATE TABLE CUSTOMERS_FLOW (
		ID NUMBER(10 , 0) NOT NULL,
		NAME VARCHAR2(20),
		STATE VARCHAR2(25),
		PHONE VARCHAR2(10)
	);

CREATE TABLE CUSTOMER_TRANS7 (
		ACCTNUM VARCHAR2(20),
		DEPTNO VARCHAR2(20),
		QUANTITY VARCHAR2(20),
		TRANSTYPE VARCHAR2(20),
		TRANSDATE VARCHAR2(20),
		NAME VARCHAR2(30),
		STREETADDRESS VARCHAR2(30),
		STATE VARCHAR2(10)
	);

CREATE TABLE DM_DCTA_EVALUATIONS (
		DPSID VARCHAR2(9) NOT NULL,
		EE_SEQ NUMBER(4 , 0) NOT NULL,
		DCTAE_TYPE VARCHAR2(10) NOT NULL,
		PLAN_CODE VARCHAR2(6) NOT NULL,
		SEMESTER_DUE VARCHAR2(10) NOT NULL,
		YEAR_DUE NUMBER(4 , 0) NOT NULL,
		JOB_FTE_CODE VARCHAR2(10),
		SRC_USER_ID VARCHAR2(10),
		SRC_UPDATE_DATE DATE
	);

CREATE TABLE DM_ORGANIZATIONAL_UNITS (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		OU_CODE VARCHAR2(5) NOT NULL,
		DESCRIPTION VARCHAR2(4000) NOT NULL,
		CREATED_BY VARCHAR2(40) NOT NULL,
		CREATION_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(40),
		LAST_UPDATE_DATE DATE
	);

CREATE TABLE PATIENT_RECORD (
		IDNUMBER VARCHAR2(8),
		NAME VARCHAR2(50),
		AGE VARCHAR2(4),
		EMAIL VARCHAR2(50),
		PHONE VARCHAR2(30),
		CREDIT_CARD VARCHAR2(20),
		DRIVING_LICENSE VARCHAR2(30),
		SSN VARCHAR2(11),
		CITY VARCHAR2(20),
		STATE VARCHAR2(20)
	);

CREATE TABLE ORDERS (
		ORDER_ID VARCHAR2(4),
		CUSTOMER VARCHAR2(200),
		EMPLOYEE VARCHAR2(200),
		SHIP_DATE TIMESTAMP,
		FREIGHT NUMBER(22 , 0)
	);

CREATE TABLE ORDERS_SORTED (
		ORDER_ID VARCHAR2(5),
		CUSTOMER VARCHAR2(200),
		EMPLOYEE VARCHAR2(200),
		SHIP_DATE TIMESTAMP,
		FREIGHT NUMBER(22 , 0)
	);

CREATE TABLE PATIENT_RECORD_ENCRYPTED (
		IDNUMBER VARCHAR2(8),
		NAME1 VARCHAR2(50),
		AGE VARCHAR2(4),
		EMAIL VARCHAR2(50),
		PHONE VARCHAR2(30),
		CREDIT_CARD VARCHAR2(20),
		DRIVING_LICENSE VARCHAR2(30),
		SSN VARCHAR2(11),
		CITY VARCHAR2(20),
		STATE VARCHAR2(20)
	);

CREATE TABLE CUSTOMERS_REP (
		SSN NUMBER(9 , 0) NOT NULL,
		LASTNAME VARCHAR2(50) NOT NULL,
		FIRSTNAME VARCHAR2(50),
		ADDRESS VARCHAR2(50),
		CITY VARCHAR2(50),
		STATE VARCHAR2(2),
		ZIP VARCHAR2(5)
	);

CREATE TABLE DM_JOB_TYPES (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		JOB_CODE VARCHAR2(5) NOT NULL,
		DESCRIPTION VARCHAR2(4000) NOT NULL,
		JOB_CLASS_CODE VARCHAR2(3),
		BIGGER_JOB_COMPANY NUMBER(4 , 0) NOT NULL,
		BIGGER_JOB_CODE VARCHAR2(5) NOT NULL,
		SUPER_JOB_COMPANY NUMBER(4 , 0) NOT NULL,
		SUPER_JOB_CODE VARCHAR2(5) NOT NULL,
		CREATED_BY VARCHAR2(40) NOT NULL,
		CREATION_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(40),
		LAST_UPDATE_DATE DATE
	);

CREATE TABLE CUSTOMER_TRANS (
		ACCTNUM VARCHAR2(20),
		DEPTNO VARCHAR2(20),
		QUANTITY VARCHAR2(20),
		TRANSTYPE VARCHAR2(20),
		TRANSDATE VARCHAR2(20),
		NAME VARCHAR2(30),
		STREETADDRESS VARCHAR2(30),
		STATE VARCHAR2(10)
	);

CREATE TABLE REGIONS (
		REGION_ID NUMBER NOT NULL,
		REGION_NAME VARCHAR2(25)
	);

CREATE TABLE COUNTRIES (
		COUNTRY_ID CHAR(2) NOT NULL,
		COUNTRY_NAME VARCHAR2(40),
		REGION_ID NUMBER
	);

CREATE TABLE DEMO2 (
		FNAME VARCHAR2(10),
		LNAME VARCHAR2(10),
		SSNO VARCHAR2(12),
		CREDITCARDNO VARCHAR2(20),
		TESTDL VARCHAR2(15),
		ADDRESS VARCHAR2(20),
		STATE VARCHAR2(20),
		COMPANY VARCHAR2(20)
	);

CREATE TABLE DEPARTMENTS (
		DEPARTMENT_ID NUMBER(4 , 0) NOT NULL,
		DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
		MANAGER_SID VARCHAR2(9),
		LOCATION_ID NUMBER(4 , 0)
	);

CREATE TABLE COMPANIES_TEST (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		COMPANY_NAME VARCHAR2(40)
	);

CREATE TABLE XL4 (
		START_TIME VARCHAR2(50),
		GLOBAL_CALL_ID VARCHAR2(50),
		DURATION VARCHAR2(50),
		CALLING_NUMBER VARCHAR2(50),
		CALLED_NUMBER VARCHAR2(50),
		TRUNK_IN VARCHAR2(50),
		TRUNK_OUT VARCHAR2(50),
		CALL_TYPE VARCHAR2(50),
		CALLING_PREFIX_CARRIER VARCHAR2(50),
		CALLED_PREFIX_CARRIER VARCHAR2(50),
		TRUNK_IN_CARRIER VARCHAR2(50),
		TRUNK_OUT_CARRIER VARCHAR2(50),
		AMOUNT VARCHAR2(50),
		CALL_SCENARIO VARCHAR2(50)
	);

CREATE TABLE PERSONS (
		SSN VARCHAR2(11) NOT NULL,
		LASTNAME VARCHAR2(50) NOT NULL,
		FIRSTNAME VARCHAR2(50),
		ADDRESS VARCHAR2(50),
		CITY VARCHAR2(50),
		STATE VARCHAR2(2),
		ZIP VARCHAR2(5),
		CREDIT_CARD VARCHAR2(19)
	);

CREATE TABLE DEMO_ROWGEN (
		FNAME VARCHAR2(20),
		LNAME VARCHAR2(20),
		SSNO VARCHAR2(20),
		CREDITCARDNO VARCHAR2(20),
		DL VARCHAR2(20),
		ADDRESS VARCHAR2(20),
		STATE VARCHAR2(20),
		COMPANY VARCHAR2(20)
	);

CREATE TABLE DM_EMPLOYEES (
		DPSID VARCHAR2(9) NOT NULL,
		EMPLOYEE_ID NUMBER NOT NULL,
		STATUS_CODE VARCHAR2(3),
		END_DATE DATE,
		HIRE_DATE DATE,
		SUPERVISOR_DPSID VARCHAR2(9),
		MANAGER_DPSID VARCHAR2(9),
		OPT_IN_DATE DATE,
		DOB DATE,
		GENDER VARCHAR2(1),
		LAST_NAME VARCHAR2(100) NOT NULL,
		FIRST_NAME VARCHAR2(100),
		MIDDLE_NAME VARCHAR2(100),
		GENERATION VARCHAR2(4),
		SSN VARCHAR2(9),
		ETHNIC_CODE VARCHAR2(3),
		EMAIL_ADDRESS VARCHAR2(60),
		ADDRESS_ID NUMBER(10 , 0),
		USER_STAMP VARCHAR2(10),
		DATE_STAMP DATE,
		TIME_STAMP NUMBER,
		CREATED_BY VARCHAR2(40) NOT NULL,
		CREATION_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(40),
		LAST_UPDATE_DATE DATE
	);

CREATE TABLE JOBS (
		JOB_ID VARCHAR2(10) NOT NULL,
		JOB_TITLE VARCHAR2(35) NOT NULL,
		MIN_SALARY NUMBER(6 , 0),
		MAX_SALARY NUMBER(6 , 0)
	);

CREATE TABLE EMPLOYEES (
		EMPLOYEE_SID VARCHAR2(9) NOT NULL,
		FIRST_NAME VARCHAR2(20),
		LAST_NAME VARCHAR2(25) NOT NULL,
		EMAIL VARCHAR2(25) NOT NULL,
		PHONE_NUMBER VARCHAR2(20),
		HIRE_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		SALARY NUMBER(8 , 2),
		COMMISSION_PCT NUMBER(3 , 2),
		MANAGER_SID VARCHAR2(9),
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE TABLE JOB_HISTORY (
		EMPLOYEE_SID VARCHAR2(9) NOT NULL,
		START_DATE DATE NOT NULL,
		END_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE TABLE DM_EMPLOYEE_EVALUATIONS (
		DPSID VARCHAR2(9) NOT NULL,
		EE_SEQ NUMBER(4 , 0) NOT NULL,
		EE_TYPE VARCHAR2(10) NOT NULL,
		STATUS_CODE VARCHAR2(10) NOT NULL,
		FREQUENCY_CODE VARCHAR2(5) NOT NULL,
		REMEDIATION_FLAG VARCHAR2(1) NOT NULL,
		SPECIAL_EVAL_FLAG VARCHAR2(1) NOT NULL,
		COMPLETE_DATE DATE,
		GOALS_MET_FLAG VARCHAR2(1),
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		JOB_CODE VARCHAR2(5),
		OU_CODE VARCHAR2(5) NOT NULL,
		CREATED_BY VARCHAR2(40) NOT NULL,
		CREATION_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(40),
		LAST_UPDATE_DATE DATE
	);

CREATE TABLE ORDERS_FLOW (
		ORDER_ID VARCHAR2(5) NOT NULL,
		CUSTOMER_ID NUMBER(10 , 0) NOT NULL,
		FREIGHT NUMBER(10 , 0),
		TOTAL NUMBER(10 , 2)
	);

CREATE TABLE CUSTOMERS_SAMPLES (
		ID NUMBER(10 , 0) NOT NULL,
		NAME VARCHAR2(20),
		STATE VARCHAR2(25),
		PHONE VARCHAR2(10)
	);

CREATE TABLE DM_COMPANIES (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		COMPANY_NAME VARCHAR2(40)
	);

CREATE TABLE YEAR_DEPT_AMT (
		YEAR NUMBER(4 , 0) NOT NULL,
		DEPT NUMBER(3 , 0) NOT NULL,
		AMT NUMBER(10 , 2) NOT NULL
	);

CREATE TABLE LOCATIONS (
		LOCATION_ID NUMBER(4 , 0) NOT NULL,
		STREET_ADDRESS VARCHAR2(40),
		POSTAL_CODE VARCHAR2(12),
		CITY VARCHAR2(30) NOT NULL,
		STATE_PROVINCE VARCHAR2(25),
		COUNTRY_ID CHAR(2)
	);

CREATE TABLE DEMO_COMPANIES (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		COMPANY_NAME VARCHAR2(40)
	);

CREATE TABLE ORDERS_SORTED (
		ORDER_ID VARCHAR2(4000),
		CUSTOMER VARCHAR2(4000),
		EMPLOYEE VARCHAR2(4000),
		SHIP_DATE TIMESTAMP(11),
		FREIGHT NUMBER(22 , 0)
	);

CREATE UNIQUE INDEX SSN_PK ON PERSONS (SSN ASC);

CREATE UNIQUE INDEX DM_COMPANIES_PK ON DM_COMPANIES (COMPANY_NUMBER ASC);

CREATE INDEX EMP_NAME_IX ON EMPLOYEES (LAST_NAME ASC, FIRST_NAME ASC);

CREATE UNIQUE INDEX SYS_C0011557 ON COMPANIES_TEST (COMPANY_NUMBER ASC);

CREATE INDEX EMP_JOB_IX ON EMPLOYEES (JOB_ID ASC);

CREATE UNIQUE INDEX ORDERS_PK ON ORDERS_FLOW (ORDER_ID ASC);

CREATE INDEX LOC_CITY_IX ON LOCATIONS (CITY ASC);

CREATE UNIQUE INDEX JHIST_EMP_ID_ST_DATE_PK ON JOB_HISTORY (EMPLOYEE_SID ASC, START_DATE ASC);

CREATE UNIQUE INDEX CUSTOMERS_PK ON CUSTOMERS_FLOW (ID ASC);

CREATE UNIQUE INDEX DM_JT_PK ON DM_JOB_TYPES (COMPANY_NUMBER ASC, JOB_CODE ASC);

CREATE UNIQUE INDEX DM_EMP_UK ON DM_EMPLOYEES (EMPLOYEE_ID ASC);

CREATE UNIQUE INDEX DM_OU_PK ON DM_ORGANIZATIONAL_UNITS (COMPANY_NUMBER ASC, OU_CODE ASC);

CREATE UNIQUE INDEX JOB_ID_PK ON JOBS (JOB_ID ASC);

CREATE INDEX LOC_STATE_PROVINCE_IX ON LOCATIONS (STATE_PROVINCE ASC);

CREATE UNIQUE INDEX COUNTRY_C_ID_PK ON COUNTRIES (COUNTRY_ID ASC);

CREATE UNIQUE INDEX REG_ID_PK ON REGIONS (REGION_ID ASC);

CREATE INDEX LOC_COUNTRY_IX ON LOCATIONS (COUNTRY_ID ASC);

CREATE UNIQUE INDEX DEPT_ID_PK ON DEPARTMENTS (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX EMP_EMAIL_UK ON EMPLOYEES (EMAIL ASC);

CREATE UNIQUE INDEX CUSTOMERS_SAMPLES_PK ON CUSTOMERS_SAMPLES (ID ASC);

CREATE INDEX DEPT_LOCATION_IX ON DEPARTMENTS (LOCATION_ID ASC);

CREATE UNIQUE INDEX DM_EMP_UK2 ON DM_EMPLOYEES (SSN ASC);

CREATE INDEX EMP_MANAGER_IX ON EMPLOYEES (MANAGER_SID ASC);

CREATE INDEX EMP_DEPARTMENT_IX ON EMPLOYEES (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX DM_EMP_PK ON DM_EMPLOYEES (DPSID ASC);

CREATE INDEX JHIST_DEPARTMENT_IX ON JOB_HISTORY (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX EMP_EMP_ID_PK ON EMPLOYEES (EMPLOYEE_SID ASC);

CREATE UNIQUE INDEX DM_EE_PK ON DM_EMPLOYEE_EVALUATIONS (DPSID ASC, EE_SEQ ASC);

CREATE INDEX JHIST_JOB_IX ON JOB_HISTORY (JOB_ID ASC);

CREATE INDEX JHIST_EMPLOYEE_IX ON JOB_HISTORY (EMPLOYEE_SID ASC);

CREATE UNIQUE INDEX CUSTOMERS_REP_SSN_PK ON CUSTOMERS_REP (SSN ASC);

CREATE UNIQUE INDEX LOC_ID_PK ON LOCATIONS (LOCATION_ID ASC);

CREATE UNIQUE INDEX DM_DCTAE_PK ON DM_DCTA_EVALUATIONS (DPSID ASC, EE_SEQ ASC);

ALTER TABLE DM_COMPANIES ADD CONSTRAINT DM_COMPANIES_PK PRIMARY KEY (COMPANY_NUMBER);

ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY (EMPLOYEE_SID);

ALTER TABLE DM_ORGANIZATIONAL_UNITS ADD CONSTRAINT DM_OU_PK PRIMARY KEY (COMPANY_NUMBER, OU_CODE);

ALTER TABLE PERSONS ADD CONSTRAINT SSN_PK PRIMARY KEY (SSN);

ALTER TABLE ORDERS_FLOW ADD CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE DM_EMPLOYEE_EVALUATIONS ADD CONSTRAINT DM_EE_PK PRIMARY KEY (DPSID, EE_SEQ);

ALTER TABLE COMPANIES_TEST ADD CONSTRAINT SYS_C0011557 PRIMARY KEY (COMPANY_NUMBER);

ALTER TABLE JOBS ADD CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID);

ALTER TABLE REGIONS ADD CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID);

ALTER TABLE DM_JOB_TYPES ADD CONSTRAINT DM_JT_PK PRIMARY KEY (COMPANY_NUMBER, JOB_CODE);

ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID);

ALTER TABLE CUSTOMERS_FLOW ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_SID, START_DATE);

ALTER TABLE CUSTOMERS_SAMPLES ADD CONSTRAINT CUSTOMERS_SAMPLES_PK PRIMARY KEY (ID);

ALTER TABLE LOCATIONS ADD CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID);

ALTER TABLE DM_EMPLOYEES ADD CONSTRAINT DM_EMP_PK PRIMARY KEY (DPSID);

ALTER TABLE DM_DCTA_EVALUATIONS ADD CONSTRAINT DM_DCTAE_PK PRIMARY KEY (DPSID, EE_SEQ);

ALTER TABLE CUSTOMERS_REP ADD CONSTRAINT CUSTOMERS_REP_SSN_PK PRIMARY KEY (SSN);

ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRY_REG_FK FOREIGN KEY (REGION_ID)
	REFERENCES REGIONS (REGION_ID);

ALTER TABLE DM_JOB_TYPES ADD CONSTRAINT DM_JT_FK_PARENT_TOP FOREIGN KEY (SUPER_JOB_COMPANY, SUPER_JOB_CODE)
	REFERENCES DM_JOB_TYPES (COMPANY_NUMBER, JOB_CODE);

ALTER TABLE DM_JOB_TYPES ADD CONSTRAINT DM_JT_COMPANIES_FK FOREIGN KEY (COMPANY_NUMBER)
	REFERENCES DM_COMPANIES (COMPANY_NUMBER);

ALTER TABLE DM_DCTA_EVALUATIONS ADD CONSTRAINT DM_EE_DCTAE_FK FOREIGN KEY (DPSID, EE_SEQ)
	REFERENCES DM_EMPLOYEE_EVALUATIONS (DPSID, EE_SEQ);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JHIS_JOB_FK FOREIGN KEY (JOB_ID)
	REFERENCES JOBS (JOB_ID);

ALTER TABLE DM_EMPLOYEE_EVALUATIONS ADD CONSTRAINT DM_EE_JT_FK FOREIGN KEY (COMPANY_NUMBER, JOB_CODE)
	REFERENCES DM_JOB_TYPES (COMPANY_NUMBER, JOB_CODE);

ALTER TABLE LOCATIONS ADD CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID)
	REFERENCES COUNTRIES (COUNTRY_ID);

ALTER TABLE DM_EMPLOYEES ADD CONSTRAINT DM_EMP_EMP_FK FOREIGN KEY (SUPERVISOR_DPSID)
	REFERENCES DM_EMPLOYEES (DPSID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_MGNR_FK FOREIGN KEY (MANAGER_SID)
	REFERENCES EMPLOYEES (EMPLOYEE_SID);

ALTER TABLE DM_ORGANIZATIONAL_UNITS ADD CONSTRAINT DM_OU_COMPANIES_FK FOREIGN KEY (COMPANY_NUMBER)
	REFERENCES DM_COMPANIES (COMPANY_NUMBER);

ALTER TABLE DM_EMPLOYEE_EVALUATIONS ADD CONSTRAINT DM_EE_EMP_FK FOREIGN KEY (DPSID)
	REFERENCES DM_EMPLOYEES (DPSID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID)
	REFERENCES JOBS (JOB_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID)
	REFERENCES LOCATIONS (LOCATION_ID);

ALTER TABLE ORDERS_FLOW ADD CONSTRAINT CUSTOMERS_FK FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMERS_FLOW (ID);

ALTER TABLE DM_EMPLOYEES ADD CONSTRAINT DM_EMP_MGR_FK FOREIGN KEY (MANAGER_DPSID)
	REFERENCES DM_EMPLOYEES (DPSID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPT_MGR_FK FOREIGN KEY (MANAGER_SID)
	REFERENCES EMPLOYEES (EMPLOYEE_SID);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JHIST_EMP_FK FOREIGN KEY (EMPLOYEE_SID)
	REFERENCES EMPLOYEES (EMPLOYEE_SID);

ALTER TABLE DM_JOB_TYPES ADD CONSTRAINT DM_JT_FK_PARENT FOREIGN KEY (BIGGER_JOB_COMPANY, BIGGER_JOB_CODE)
	REFERENCES DM_JOB_TYPES (COMPANY_NUMBER, JOB_CODE);

ALTER TABLE DM_EMPLOYEE_EVALUATIONS ADD CONSTRAINT DM_EE_OU_FK FOREIGN KEY (COMPANY_NUMBER, OU_CODE)
	REFERENCES DM_ORGANIZATIONAL_UNITS (COMPANY_NUMBER, OU_CODE);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DEPARTMENTS (DEPARTMENT_ID);
