--<ScriptOptions statementTerminator=";"/>

ALTER TABLE LOCATIONS DROP CONSTRAINT L_C_ID_FK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT D_L_ID_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JH_J_ID_FK;

ALTER TABLE COUNTRIES DROP CONSTRAINT C_R_ID_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT E_D_ID_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT E_J_ID_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JH_D_ID_FK;

ALTER TABLE DM_JOB_TYPES DROP CONSTRAINT DM_JT_FK_PARENT_TOP;

ALTER TABLE DM_JOB_TYPES DROP CONSTRAINT DM_JT_COMPANIES_FK;

ALTER TABLE DM_DCTA_EVALUATIONS DROP CONSTRAINT DM_EE_DCTAE_FK;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DROP CONSTRAINT DM_EE_JT_FK;

ALTER TABLE DM_EMPLOYEES DROP CONSTRAINT DM_EMP_EMP_FK;

ALTER TABLE DM_ORGANIZATIONAL_UNITS DROP CONSTRAINT DM_OU_COMPANIES_FK;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DROP CONSTRAINT DM_EE_EMP_FK;

ALTER TABLE ORDERS_FLOW DROP CONSTRAINT CUSTOMERS_FK;

ALTER TABLE DM_EMPLOYEES DROP CONSTRAINT DM_EMP_MGR_FK;

ALTER TABLE DM_JOB_TYPES DROP CONSTRAINT DM_JT_FK_PARENT;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DROP CONSTRAINT DM_EE_OU_FK;

ALTER TABLE ORDERS_NF DROP CONSTRAINT CUSTOMERS_ORDERS_NF_FK);

ALTER TABLE SUB_SALE_DIM DROP CONSTRAINT SUB_SALE_DIM_FK1;

ALTER TABLE SUB_SALE_DIM DROP CONSTRAINT SUB_SALE_DIM_FK2;

ALTER TABLE SUB_SALE_DIM DROP CONSTRAINT SUB_SALE_DIM_FK3;

ALTER TABLE SUB_SALE_DIM DROP CONSTRAINT SUB_SALE_DIM_FK4;

ALTER TABLE SUB_SALE_DIM DROP CONSTRAINT SUB_SALE_DIM_FK5;

ALTER TABLE SUB_SALE_DIM DROP CONSTRAINT SUB_SALE_DIM_FK6;

ALTER TABLE SUB_SALE_DIM DROP CONSTRAINT SUB_SALE_DIM_FK7;

ALTER TABLE SALE_DIM ADD CONSTRAINT PROJECT_DIM_FK;

ALTER TABLE SALE_DIM DROP CONSTRAINT ITEM_PRICE_RANGE_DIM_FK;

ALTER TABLE SALE_DIM DROP CONSTRAINT ITEM_DIM_FK;

ALTER TABLE SALE_DIM DROP CONSTRAINT EMP_SALARY_RANGE_DIM_FK;

ALTER TABLE SALE_DIM DROP CONSTRAINT CATEGORY_DIM_FK;

ALTER TABLE SALE_DIM DROP CONSTRAINT DEPT_DIM_FK;

ALTER TABLE SALE_DIM DROP CONSTRAINT EMP_DIM_FK;

ALTER TABLE DM_COMPANIES DROP CONSTRAINT DM_COMPANIES_PK;

ALTER TABLE DM_ORGANIZATIONAL_UNITS DROP CONSTRAINT DM_OU_PK;

ALTER TABLE PERSONS DROP CONSTRAINT SSN_PK;

ALTER TABLE ORDERS_FLOW DROP CONSTRAINT ORDERS_PK;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DROP CONSTRAINT DM_EE_PK;

ALTER TABLE COMPANIES_TEST DROP CONSTRAINT SYS_C0011557;

ALTER TABLE DM_JOB_TYPES DROP CONSTRAINT DM_JT_PK;

ALTER TABLE CUSTOMERS_FLOW DROP CONSTRAINT CUSTOMERS_PK;

ALTER TABLE CUSTOMERS_SAMPLES DROP CONSTRAINT CUSTOMERS_SAMPLES_PK;

ALTER TABLE DM_EMPLOYEES DROP CONSTRAINT DM_EMP_PK;

ALTER TABLE DM_DCTA_EVALUATIONS DROP CONSTRAINT DM_DCTAE_PK;

ALTER TABLE CUSTOMERS_REP DROP CONSTRAINT CUSTOMERS_REP_SSN_PK;

ALTER TABLE ORDERS_NF DROP CONSTRAINT ORDERS_NF_ORDER_ID_PK;

ALTER TABLE CUSTOMERS_NF DROP CONSTRAINT CUSTOMERS_NF_ID_PK;

ALTER TABLE SUB_CATEGORY_DIM DROP CONSTRAINT SUB_CATEGORY_DIM_PK;

ALTER TABLE SUB_DEPT_DIM DROP CONSTRAINT SUB_DEPT_DIM_PK ;

ALTER TABLE SUB_EMP_DIM DROP CONSTRAINT SUB_EMP_DIM_PK;

ALTER TABLE SUB_EMP_SALARY_RANGE_DIM DROP CONSTRAINT SUB_EMP_SALARY_RANGE_DIM_PK ;

ALTER TABLE SUB_ITEM_DIM DROP CONSTRAINT SUB_ITEM_DIM_PK;

ALTER TABLE SUB_ITEM_PRICE_RANGE_DIM DROP CONSTRAINT SUB_ITEM_PRICE_RANGE_DIM_PK;

ALTER TABLE SUB_PROJECT_DIM DROP CONSTRAINT SUB_PROJECT_DIM_PK;

ALTER TABLE SUB_SALE_DIM DROP CONSTRAINT SUB_SALE_DIM_PK;

ALTER TABLE PROJECT_DIM DROP CONSTRAINT PROJECT_DIM_PK;

ALTER TABLE ITEM_PRICE_RANGE_DIM DROP CONSTRAINT ITEM_PRICE_RANGE_DIM_PK;

ALTER TABLE ITEM_DIM DROP CONSTRAINT ITEM_DIM_PK;

ALTER TABLE EMP_SALARY_RANGE_DIM DROP CONSTRAINT EMP_SALARY_RANGE_DIM_PK;

ALTER TABLE EMP_DIM DROP CONSTRAINT EMP_DIM_PK;

ALTER TABLE DEPT_DIM DROP CONSTRAINT DEPT_DIM_PK;

ALTER TABLE CATEGORY_DIM DROP CONSTRAINT CATEGORY_DIM_PK;

ALTER TABLE SALE_DIM DROP CONSTRAINT SALE_DIM_PK;


DROP INDEX L_L_ID_PK;

DROP INDEX E_E_SID_UK;

DROP INDEX J_J_ID_PK;

DROP INDEX D_D_ID_PK;

DROP INDEX JH_E_SID_SD_UK;

DROP INDEX E_ID_PK;

DROP INDEX C_C_ID_PK;

DROP INDEX JH_ID_PK;

DROP INDEX R_R_ID_PK;

DROP INDEX SSN_PK;

DROP INDEX DM_COMPANIES_PK;

DROP INDEX SYS_C0011557;

DROP INDEX ORDERS_PK;

DROP INDEX CUSTOMERS_PK;

DROP INDEX DM_JT_PK;

DROP INDEX DM_EMP_UK;

DROP INDEX DM_OU_PK;

DROP INDEX CUSTOMERS_SAMPLES_PK;

DROP INDEX DM_EMP_UK2;

DROP INDEX DM_EMP_PK;

DROP INDEX DM_EE_PK;

DROP INDEX CUSTOMERS_REP_SSN_PK;

DROP INDEX DM_DCTAE_PK;

DROP INDEX ORDERS_NF_ORDER_ID_PK;

DROP INDEX CUSTOMERS_NF_ID_PK;

DROP INDEX SUB_CATEGORY_DIM_PK;

DROP INDEX SUB_DEPT_DIM_PK ;

DROP INDEX SUB_EMP_DIM_PK;

DROP INDEX SUB_EMP_SALARY_RANGE_DIM_PK ;

DROP INDEX SUB_ITEM_DIM_PK;

DROP INDEX SUB_ITEM_PRICE_RANGE_DIM_PK;

DROP INDEX SUB_PROJECT_DIM_PK;

DROP INDEX SUB_SALE_DIM_PK;

DROP INDEX PROJECT_DIM_PK;

DROP INDEX ITEM_PRICE_RANGE_DIM_PK;

DROP INDEX ITEM_DIM_PK;

DROP INDEX EMP_SALARY_RANGE_DIM_PK;

DROP INDEX EMP_DIM_PK;

DROP INDEX DEPT_DIM_PK;

DROP INDEX CATEGORY_DIM_PK;

DROP INDEX SALE_DIM_PK;


DROP TABLE CUSTOMERS_FLOW;

DROP TABLE DM_DCTA_EVALUATIONS;

DROP TABLE DM_ORGANIZATIONAL_UNITS;

DROP TABLE PATIENT_RECORD;

DROP TABLE PATIENT_RECORD_ENCRYPTED;

DROP TABLE CUSTOMERS_REP;

DROP TABLE DM_JOB_TYPES;

DROP TABLE CUSTOMER_TRANS;

DROP TABLE REGIONS;

DROP TABLE COUNTRIES;

DROP TABLE DEPARTMENTS;

DROP TABLE COMPANIES_TEST;

DROP TABLE XL4;

DROP TABLE PERSONS;

DROP TABLE DEMO_ROWGEN;

DROP TABLE DM_EMPLOYEES;

DROP TABLE JOBS;

DROP TABLE EMPLOYEES;

DROP TABLE JOB_HISTORY;

DROP TABLE DM_EMPLOYEE_EVALUATIONS;

DROP TABLE ORDERS;

DROP TABLE ORDERS_SORTED;

DROP TABLE ORDERS_FLOW;

DROP TABLE CUSTOMERS_SAMPLES;

DROP TABLE DM_COMPANIES;

DROP TABLE YEAR_DEPT_AMT;

DROP TABLE LOCATIONS;

DROP TABLE DEMO_COMPANIES;

DROP TABLE ORDERS_NF;

DROP TABLE CUSTOMERS_NF;

DROP TABLE SUB_CATEGORY_DIM;

DROP TABLE SUB_DEPT_DIM;

DROP TABLE SUB_EMP_DIM;

DROP TABLE SUB_EMP_SALARY_RANGE_DIM;

DROP TABLE SUB_ITEM_DIM;

DROP TABLE SUB_ITEM_PRICE_RANGE_DIM;

DROP TABLE SUB_PROJECT_DIM;

DROP TABLE SUB_SALE_DIM;

DROP TABLE PROJECT_DIM;

DROP TABLE ITEM_PRICE_RANGE_DIM;

DROP TABLE ITEM_DIM;

DROP TABLE EMP_SALARY_RANGE_DIM;

DROP TABLE EMP_DIM;

DROP TABLE DEPT_DIM;

DROP TABLE CATEGORY_DIM;

DROP TABLE SALE_DIM;



CREATE TABLE CUSTOMERS_FLOW (
		ID NUMBER(10 , 0) NOT NULL,
		NAME VARCHAR2(20),
		STATE VARCHAR2(25),
		PHONE VARCHAR2(10)
	);

CREATE TABLE DM_DCTA_EVALUATIONS (
		DPSID VARCHAR2(9) NOT NULL,
		EE_SEQ NUMBER(4 , 0) NOT NULL,
		DCTAE_TYPE VARCHAR2(10) NOT NULL,
		PLAN_CODE VARCHAR2(6) NOT NULL,
		SEMESTER_DUE VARCHAR2(10) NOT NULL,
		YEAR_DUE NUMBER(4 , 0) NOT NULL,
		JOB_FTE_CODE VARCHAR2(10),
		SRC_USER_ID VARCHAR2(10),
		SRC_UPDATE_DATE DATE
	);

CREATE TABLE DM_ORGANIZATIONAL_UNITS (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		OU_CODE VARCHAR2(5) NOT NULL,
		DESCRIPTION VARCHAR2(4000) NOT NULL,
		CREATED_BY VARCHAR2(40) NOT NULL,
		CREATION_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(40),
		LAST_UPDATE_DATE DATE
	);

CREATE TABLE PATIENT_RECORD (
		IDNUMBER VARCHAR2(8),
		NAME VARCHAR2(50),
		AGE VARCHAR2(4),
		EMAIL VARCHAR2(50),
		PHONE VARCHAR2(30),
		CREDIT_CARD VARCHAR2(20),
		DRIVING_LICENSE VARCHAR2(30),
		SSN VARCHAR2(11),
		CITY VARCHAR2(20),
		STATE VARCHAR2(20)
	);

CREATE TABLE ORDERS (
		ORDER_ID VARCHAR2(5),
		CUSTOMER VARCHAR2(50),
		EMPLOYEE VARCHAR2(50),
		SHIP_DATE TIMESTAMP,
		FREIGHT NUMBER(22 , 0)
	);

CREATE TABLE ORDERS_SORTED (
		ORDER_ID VARCHAR2(5),
		CUSTOMER VARCHAR2(50),
		EMPLOYEE VARCHAR2(50),
		SHIP_DATE TIMESTAMP,
		FREIGHT NUMBER(22 , 0)
	);

CREATE TABLE PATIENT_RECORD_ENCRYPTED (
		IDNUMBER VARCHAR2(8),
		NAME VARCHAR2(50),
		AGE VARCHAR2(4),
		EMAIL VARCHAR2(50),
		PHONE VARCHAR2(30),
		CREDIT_CARD VARCHAR2(20),
		DRIVING_LICENSE VARCHAR2(30),
		SSN VARCHAR2(11),
		CITY VARCHAR2(20),
		STATE VARCHAR2(20)
	);

CREATE TABLE CUSTOMERS_REP (
		SSN NUMBER(9 , 0) NOT NULL,
		LASTNAME VARCHAR2(50) NOT NULL,
		FIRSTNAME VARCHAR2(50),
		ADDRESS VARCHAR2(50),
		CITY VARCHAR2(50),
		STATE VARCHAR2(2),
		ZIP VARCHAR2(5)
	);

CREATE TABLE DM_JOB_TYPES (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		JOB_CODE VARCHAR2(5) NOT NULL,
		DESCRIPTION VARCHAR2(4000) NOT NULL,
		JOB_CLASS_CODE VARCHAR2(3),
		BIGGER_JOB_COMPANY NUMBER(4 , 0) NOT NULL,
		BIGGER_JOB_CODE VARCHAR2(5) NOT NULL,
		SUPER_JOB_COMPANY NUMBER(4 , 0) NOT NULL,
		SUPER_JOB_CODE VARCHAR2(5) NOT NULL,
		CREATED_BY VARCHAR2(40) NOT NULL,
		CREATION_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(40),
		LAST_UPDATE_DATE DATE
	);

CREATE TABLE CUSTOMER_TRANS (
		ACCTNUM VARCHAR2(20),
		DEPTNO VARCHAR2(20),
		QUANTITY VARCHAR2(20),
		TRANSTYPE VARCHAR2(20),
		TRANSDATE VARCHAR2(20),
		NAME VARCHAR2(30),
		STREETADDRESS VARCHAR2(30),
		STATE VARCHAR2(10)
	);

CREATE TABLE REGIONS (
		REGION_ID NUMBER NOT NULL,
		REGION_NAME VARCHAR2(25)
	);

CREATE TABLE COUNTRIES (
		COUNTRY_ID CHAR(2) NOT NULL,
		COUNTRY_NAME VARCHAR2(40),
		REGION_ID NUMBER
	);

CREATE TABLE DEPARTMENTS (
		DEPARTMENT_ID NUMBER(4 , 0) NOT NULL,
		DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
		MANAGER_SID VARCHAR2(9),
		LOCATION_ID NUMBER(4 , 0)
	);

CREATE TABLE COMPANIES_TEST (
		COMPANY_NUMBER NUMERIC(19,0),
		COMPANY_NAME VARCHAR2(40)
	);

CREATE TABLE XL4 (
		START_TIME VARCHAR2(50),
		GLOBAL_CALL_ID VARCHAR2(50),
		DURATION VARCHAR2(50),
		CALLING_NUMBER VARCHAR2(50),
		CALLED_NUMBER VARCHAR2(50),
		TRUNK_IN VARCHAR2(50),
		TRUNK_OUT VARCHAR2(50),
		CALL_TYPE VARCHAR2(50),
		CALLING_PREFIX_CARRIER VARCHAR2(50),
		CALLED_PREFIX_CARRIER VARCHAR2(50),
		TRUNK_IN_CARRIER VARCHAR2(50),
		TRUNK_OUT_CARRIER VARCHAR2(50),
		AMOUNT VARCHAR2(50),
		CALL_SCENARIO VARCHAR2(50)
	);

CREATE TABLE PERSONS (
		SSN VARCHAR2(11) NOT NULL,
		LASTNAME VARCHAR2(50) NOT NULL,
		FIRSTNAME VARCHAR2(50),
		ADDRESS VARCHAR2(50),
		CITY VARCHAR2(50),
		STATE VARCHAR2(2),
		ZIP VARCHAR2(5),
		CREDIT_CARD VARCHAR2(19)
	);

CREATE TABLE DEMO_ROWGEN (
		FNAME VARCHAR2(20),
		LNAME VARCHAR2(20),
		SSNO VARCHAR2(20),
		CREDITCARDNO VARCHAR2(20),
		DL VARCHAR2(20),
		ADDRESS VARCHAR2(20),
		STATE VARCHAR2(20),
		COMPANY VARCHAR2(20)
	);

CREATE TABLE DM_EMPLOYEES (
		DPSID VARCHAR2(9) NOT NULL,
		EMPLOYEE_ID NUMBER NOT NULL,
		STATUS_CODE VARCHAR2(3),
		END_DATE DATE,
		HIRE_DATE DATE,
		SUPERVISOR_DPSID VARCHAR2(9),
		MANAGER_DPSID VARCHAR2(9),
		OPT_IN_DATE DATE,
		DOB DATE,
		GENDER VARCHAR2(1),
		LAST_NAME VARCHAR2(100) NOT NULL,
		FIRST_NAME VARCHAR2(100),
		MIDDLE_NAME VARCHAR2(100),
		GENERATION VARCHAR2(4),
		SSN VARCHAR2(9),
		ETHNIC_CODE VARCHAR2(3),
		EMAIL_ADDRESS VARCHAR2(60),
		ADDRESS_ID NUMBER(10 , 0),
		USER_STAMP VARCHAR2(10),
		DATE_STAMP DATE,
		TIME_STAMP NUMBER,
		CREATED_BY VARCHAR2(40) NOT NULL,
		CREATION_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(40),
		LAST_UPDATE_DATE DATE
	);

CREATE TABLE JOBS (
		JOB_ID VARCHAR2(10) NOT NULL,
		JOB_TITLE VARCHAR2(35) NOT NULL,
		MIN_SALARY NUMBER(6 , 0),
		MAX_SALARY NUMBER(6 , 0)
	);

CREATE TABLE EMPLOYEES (
		ID INTEGER NOT NULL,
		EMPLOYEE_SID VARCHAR2(9) NOT NULL,
		FIRST_NAME VARCHAR2(20),
		LAST_NAME VARCHAR2(25) NOT NULL,
		EMAIL VARCHAR2(50) NOT NULL,
		PHONE_NUMBER VARCHAR2(20),
		HIRE_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		SALARY NUMBER(8 , 2),
		COMMISSION_PCT NUMBER(3 , 2),
		MANAGER_SID VARCHAR2(9),
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE TABLE JOB_HISTORY (
		ID INTEGER NOT NULL,
		EMPLOYEE_SID VARCHAR2(9) NOT NULL,
		START_DATE DATE NOT NULL,
		END_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE TABLE DM_EMPLOYEE_EVALUATIONS (
		DPSID VARCHAR2(9) NOT NULL,
		EE_SEQ NUMBER(4 , 0) NOT NULL,
		EE_TYPE VARCHAR2(10) NOT NULL,
		STATUS_CODE VARCHAR2(10) NOT NULL,
		FREQUENCY_CODE VARCHAR2(5) NOT NULL,
		REMEDIATION_FLAG VARCHAR2(1) NOT NULL,
		SPECIAL_EVAL_FLAG VARCHAR2(1) NOT NULL,
		COMPLETE_DATE DATE,
		GOALS_MET_FLAG VARCHAR2(1),
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		JOB_CODE VARCHAR2(5),
		OU_CODE VARCHAR2(5) NOT NULL,
		CREATED_BY VARCHAR2(40) NOT NULL,
		CREATION_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(40),
		LAST_UPDATE_DATE DATE
	);

CREATE TABLE ORDERS_FLOW (
		ORDER_ID VARCHAR2(5) NOT NULL,
		CUSTOMER_ID NUMBER(10 , 0) NOT NULL,
		FREIGHT NUMBER(10 , 0),
		TOTAL NUMBER(10 , 2)
	);

CREATE TABLE CUSTOMERS_SAMPLES (
		ID NUMBER(10 , 0) NOT NULL,
		NAME VARCHAR2(20),
		STATE VARCHAR2(25),
		PHONE VARCHAR2(10)
	);

CREATE TABLE DM_COMPANIES (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		COMPANY_NAME VARCHAR2(40)
	);

CREATE TABLE YEAR_DEPT_AMT (
		YEAR NUMBER(4 , 0) NOT NULL,
		DEPT NUMBER(3 , 0) NOT NULL,
		AMT NUMBER(10 , 2) NOT NULL
	);

CREATE TABLE LOCATIONS (
		LOCATION_ID NUMBER(4 , 0) NOT NULL,
		STREET_ADDRESS VARCHAR2(40),
		POSTAL_CODE VARCHAR2(12),
		CITY VARCHAR2(30) NOT NULL,
		STATE_PROVINCE VARCHAR2(25),
		COUNTRY_ID CHAR(2)
	);

CREATE TABLE DEMO_COMPANIES (
		COMPANY_NUMBER NUMBER(4 , 0) NOT NULL,
		COMPANY_NAME VARCHAR2(40)
	);

CREATE TABLE CUSTOMERS_NF (
		ID NUMERIC(5, 0) NOT NULL,
		NAME VARCHAR(20) NOT NULL,
		ADDRESS VARCHAR(25),
		PHONE VARCHAR(10)
	);

CREATE TABLE ORDERS_NF (
		ORDER_ID VARCHAR(5) NOT NULL,
		CUSTOMER_ID NUMERIC(5) NOT NULL,
		FREIGHT NUMERIC(5, 0),
		TOTAL NUMERIC(10, 2)
	);

CREATE TABLE SUB_CATEGORY_DIM (
		CATEGORY_ID NUMBER(20,2) NOT NULL,
		CATEGORY_NAME VARCHAR2(70)
	);

CREATE TABLE SUB_DEPT_DIM (
		DEPT_ID NUMBER(20,2) NOT NULL,
		DEPT_NAME VARCHAR2(30)
	);

CREATE TABLE SUB_EMP_DIM (
		EMP_ID NUMBER(20,2) NOT NULL,
		EMP_NAME VARCHAR2(30)
	);

CREATE TABLE SUB_EMP_SALARY_RANGE_DIM (
		EMP_SALARY_RANGE_ID NUMBER(20,2) NOT NULL,
		RANGE_NAME VARCHAR2(30),
		RANGE_START NUMBER(20,2),
		RANGE_END NUMBER(20,2)
	);

CREATE TABLE SUB_ITEM_DIM (
		ITEM_ID NUMBER(20,2) NOT NULL,
		ITEM_NAME VARCHAR2(30)
	);

CREATE TABLE SUB_ITEM_PRICE_RANGE_DIM (
		ITEM_PRICE_RANGE_ID NUMBER(20,2) NOT NULL,
		RANGE_NAME VARCHAR2(30),
		RANGE_START NUMBER(20,2),
		RANGE_END NUMBER(20,2)
	);

CREATE TABLE SUB_PROJECT_DIM (
		PROJECT_ID NUMBER(20,2) NOT NULL,
		PROJECT_NAME VARCHAR2(30)
	);

CREATE TABLE SUB_SALE_DIM (
		SALE_ID NUMBER(20,2) NOT NULL,
		SALE_DATE DATE,
		QTY_SOLD NUMBER(20,2),
		DEPT_ID NUMBER(20,2),
		EMP_ID NUMBER(20,2),
		PROJECT_ID NUMBER(20,2),
		ITEM_ID NUMBER(20,2),
		CATEGORY_ID NUMBER(20,2),
		EMP_SALARY_RANGE_ID NUMBER(20,2),
		ITEM_PRICE_RANGE_ID NUMBER(20,2)
	);

CREATE TABLE PROJECT_DIM (
	PROJECT_ID NUMBER(22) NOT NULL,
	PROJECT_NAME VARCHAR2(30)
	);

CREATE TABLE ITEM_PRICE_RANGE_DIM (
	ITEM_PRICE_RANGE_ID NUMBER(22) NOT NULL,
	RANGE_NAME VARCHAR2(30),
	RANGE_START NUMBER(22),
	RANGE_END NUMBER(22)
	);

CREATE TABLE ITEM_DIM (
	ITEM_ID NUMBER(22) NOT NULL,
	ITEM_NAME VARCHAR2(30)
	);

CREATE TABLE EMP_SALARY_RANGE_DIM (
	EMP_SALARY_RANGE_ID NUMBER(22) NOT NULL,
	RANGE_NAME VARCHAR2(30),
	RANGE_START NUMBER(22),
	RANGE_END NUMBER(22)
	);

CREATE TABLE EMP_DIM (
	EMP_ID NUMBER(22) NOT NULL,
	EMP_NAME VARCHAR2(30)
	);

CREATE TABLE DEPT_DIM (
	DEPT_ID NUMBER(22) NOT NULL,
	DEPT_NAME VARCHAR2(30)
	);

CREATE TABLE CATEGORY_DIM (
	CATEGORY_ID NUMBER(22) NOT NULL,
	CATEGORY_NAME VARCHAR2(70)
	);

CREATE TABLE SALE_DIM (
	SALE_ID NUMBER(22) NOT NULL,
	SALE_DATE DATE,
	QTY_SOLD NUMBER(22),
	DEPT_ID NUMBER(22),
	EMP_ID NUMBER(22),
	PROJECT_ID NUMBER(22),
	ITEM_ID NUMBER(22),
	CATEGORY_ID NUMBER(22),
	EMP_SALARY_RANGE_ID NUMBER(22),
	ITEM_PRICE_RANGE_ID NUMBER(22)
	);


CREATE UNIQUE INDEX L_L_ID_PK ON LOCATIONS (LOCATION_ID ASC);

CREATE UNIQUE INDEX E_E_SID_UK ON EMPLOYEES (EMPLOYEE_SID ASC);

CREATE UNIQUE INDEX J_J_ID_PK ON JOBS (JOB_ID ASC);

CREATE UNIQUE INDEX D_D_ID_PK ON DEPARTMENTS (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX JH_E_SID_SD_UK ON JOB_HISTORY (EMPLOYEE_SID ASC, START_DATE ASC);

CREATE UNIQUE INDEX E_ID_PK ON EMPLOYEES (ID ASC);

CREATE UNIQUE INDEX C_C_ID_PK ON COUNTRIES (COUNTRY_ID ASC);

CREATE UNIQUE INDEX JH_ID_PK ON JOB_HISTORY (ID ASC);

CREATE UNIQUE INDEX R_R_ID_PK ON REGIONS (REGION_ID ASC);

CREATE UNIQUE INDEX SSN_PK ON PERSONS (SSN ASC);

CREATE UNIQUE INDEX DM_COMPANIES_PK ON DM_COMPANIES (COMPANY_NUMBER ASC);

CREATE UNIQUE INDEX SYS_C0011557 ON COMPANIES_TEST (COMPANY_NUMBER ASC);

CREATE UNIQUE INDEX ORDERS_PK ON ORDERS_FLOW (ORDER_ID ASC);

CREATE UNIQUE INDEX CUSTOMERS_PK ON CUSTOMERS_FLOW (ID ASC);

CREATE UNIQUE INDEX DM_JT_PK ON DM_JOB_TYPES (COMPANY_NUMBER ASC, JOB_CODE ASC);

CREATE UNIQUE INDEX DM_EMP_UK ON DM_EMPLOYEES (EMPLOYEE_ID ASC);

CREATE UNIQUE INDEX DM_OU_PK ON DM_ORGANIZATIONAL_UNITS (COMPANY_NUMBER ASC, OU_CODE ASC);

CREATE UNIQUE INDEX CUSTOMERS_SAMPLES_PK ON CUSTOMERS_SAMPLES (ID ASC);

CREATE UNIQUE INDEX DM_EMP_UK2 ON DM_EMPLOYEES (SSN ASC);

CREATE UNIQUE INDEX DM_EMP_PK ON DM_EMPLOYEES (DPSID ASC);

CREATE UNIQUE INDEX DM_EE_PK ON DM_EMPLOYEE_EVALUATIONS (DPSID ASC, EE_SEQ ASC);

CREATE UNIQUE INDEX CUSTOMERS_REP_SSN_PK ON CUSTOMERS_REP (SSN ASC);

CREATE UNIQUE INDEX DM_DCTAE_PK ON DM_DCTA_EVALUATIONS (DPSID ASC, EE_SEQ ASC);

CREATE UNIQUE INDEX CUSTOMERS_NF_ID_PK ON CUSTOMERS_NF (ID ASC);

CREATE UNIQUE INDEX ORDERS_NF_ORDER_ID_PK ON ORDERS_NF (ORDER_ID ASC);


ALTER TABLE COUNTRIES ADD CONSTRAINT C_C_ID_PK PRIMARY KEY (COUNTRY_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT D_D_ID_PK PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE LOCATIONS ADD CONSTRAINT L_L_ID_PK PRIMARY KEY (LOCATION_ID);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JH_ID_PK PRIMARY KEY (ID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT E_ID_PK PRIMARY KEY (ID);

ALTER TABLE JOBS ADD CONSTRAINT J_J_ID_PK PRIMARY KEY (JOB_ID);

ALTER TABLE REGIONS ADD CONSTRAINT R_R_ID_PK PRIMARY KEY (REGION_ID);

ALTER TABLE DM_COMPANIES ADD CONSTRAINT DM_COMPANIES_PK PRIMARY KEY (COMPANY_NUMBER);

ALTER TABLE DM_ORGANIZATIONAL_UNITS ADD CONSTRAINT DM_OU_PK PRIMARY KEY (COMPANY_NUMBER, OU_CODE);

ALTER TABLE PERSONS ADD CONSTRAINT SSN_PK PRIMARY KEY (SSN);

ALTER TABLE ORDERS_FLOW ADD CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID);

ALTER TABLE DM_EMPLOYEE_EVALUATIONS ADD CONSTRAINT DM_EE_PK PRIMARY KEY (DPSID, EE_SEQ);

ALTER TABLE COMPANIES_TEST ADD CONSTRAINT SYS_C0011557 PRIMARY KEY (COMPANY_NUMBER);

ALTER TABLE DM_JOB_TYPES ADD CONSTRAINT DM_JT_PK PRIMARY KEY (COMPANY_NUMBER, JOB_CODE);

ALTER TABLE CUSTOMERS_FLOW ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID);

ALTER TABLE CUSTOMERS_SAMPLES ADD CONSTRAINT CUSTOMERS_SAMPLES_PK PRIMARY KEY (ID);

ALTER TABLE DM_EMPLOYEES ADD CONSTRAINT DM_EMP_PK PRIMARY KEY (DPSID);

ALTER TABLE DM_DCTA_EVALUATIONS ADD CONSTRAINT DM_DCTAE_PK PRIMARY KEY (DPSID, EE_SEQ);

ALTER TABLE CUSTOMERS_REP ADD CONSTRAINT CUSTOMERS_REP_SSN_PK PRIMARY KEY (SSN);

ALTER TABLE CUSTOMERS_NF ADD CONSTRAINT CUSTOMERS_NF_ID_PK PRIMARY KEY (ID);

ALTER TABLE ORDERS_NF ADD CONSTRAINT ORDERS_NF_ORDER_ID_PK PRIMARY KEY (ORDER_ID);

ALTER TABLE SUB_CATEGORY_DIM ADD CONSTRAINT SUB_CATEGORY_DIM_PK PRIMARY KEY (CATEGORY_ID);

ALTER TABLE SUB_DEPT_DIM ADD CONSTRAINT SUB_DEPT_DIM_PK PRIMARY KEY (DEPT_ID);

ALTER TABLE SUB_EMP_DIM ADD CONSTRAINT SUB_EMP_DIM_PK PRIMARY KEY (EMP_ID);

ALTER TABLE SUB_EMP_SALARY_RANGE_DIM ADD CONSTRAINT SUB_EMP_SALARY_RANGE_DIM_PK PRIMARY KEY (EMP_SALARY_RANGE_ID);

ALTER TABLE SUB_ITEM_DIM ADD CONSTRAINT SUB_ITEM_DIM_PK PRIMARY KEY (ITEM_ID);

ALTER TABLE SUB_ITEM_PRICE_RANGE_DIM ADD CONSTRAINT SUB_ITEM_PRICE_RANGE_DIM_PK PRIMARY KEY (ITEM_PRICE_RANGE_ID);

ALTER TABLE SUB_PROJECT_DIM ADD CONSTRAINT SUB_PROJECT_DIM_PK PRIMARY KEY (PROJECT_ID);

ALTER TABLE SUB_SALE_DIM ADD CONSTRAINT SUB_SALE_DIM_PK PRIMARY KEY (SALE_ID);

ALTER TABLE PROJECT_DIM ADD CONSTRAINT PROJECT_DIM_PK PRIMARY KEY (PROJECT_ID);

ALTER TABLE ITEM_PRICE_RANGE_DIM ADD CONSTRAINT ITEM_PRICE_RANGE_DIM_PK PRIMARY KEY (ITEM_PRICE_RANGE_ID);

ALTER TABLE ITEM_DIM ADD CONSTRAINT ITEM_DIM_PK PRIMARY KEY (ITEM_ID);

ALTER TABLE EMP_SALARY_RANGE_DIM ADD CONSTRAINT EMP_SALARY_RANGE_DIM_PK PRIMARY KEY (EMP_SALARY_RANGE_ID);

ALTER TABLE EMP_DIM ADD CONSTRAINT EMP_DIM_PK PRIMARY KEY (EMP_ID);

ALTER TABLE DEPT_DIM ADD CONSTRAINT DEPT_DIM_PK PRIMARY KEY (DEPT_ID);

ALTER TABLE CATEGORY_DIM ADD CONSTRAINT CATEGORY_DIM_PK PRIMARY KEY (CATEGORY_ID);

ALTER TABLE SALE_DIM ADD CONSTRAINT SALE_DIM_PK PRIMARY KEY (SALE_ID);

ALTER TABLE LOCATIONS ADD CONSTRAINT L_C_ID_FK FOREIGN KEY (COUNTRY_ID)
	REFERENCES COUNTRIES (COUNTRY_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT D_L_ID_FK FOREIGN KEY (LOCATION_ID)
	REFERENCES LOCATIONS (LOCATION_ID);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JH_J_ID_FK FOREIGN KEY (JOB_ID)
	REFERENCES JOBS (JOB_ID);

ALTER TABLE COUNTRIES ADD CONSTRAINT C_R_ID_FK FOREIGN KEY (REGION_ID)
	REFERENCES REGIONS (REGION_ID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT E_D_ID_FK FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT E_J_ID_FK FOREIGN KEY (JOB_ID)
	REFERENCES JOBS (JOB_ID);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JH_D_ID_FK FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE DM_JOB_TYPES ADD CONSTRAINT DM_JT_FK_PARENT_TOP FOREIGN KEY (SUPER_JOB_COMPANY, SUPER_JOB_CODE)
	REFERENCES DM_JOB_TYPES (COMPANY_NUMBER, JOB_CODE);

ALTER TABLE DM_JOB_TYPES ADD CONSTRAINT DM_JT_COMPANIES_FK FOREIGN KEY (COMPANY_NUMBER)
	REFERENCES DM_COMPANIES (COMPANY_NUMBER);

ALTER TABLE DM_DCTA_EVALUATIONS ADD CONSTRAINT DM_EE_DCTAE_FK FOREIGN KEY (DPSID, EE_SEQ)
	REFERENCES DM_EMPLOYEE_EVALUATIONS (DPSID, EE_SEQ);

ALTER TABLE DM_EMPLOYEE_EVALUATIONS ADD CONSTRAINT DM_EE_JT_FK FOREIGN KEY (COMPANY_NUMBER, JOB_CODE)
	REFERENCES DM_JOB_TYPES (COMPANY_NUMBER, JOB_CODE);

ALTER TABLE DM_EMPLOYEES ADD CONSTRAINT DM_EMP_EMP_FK FOREIGN KEY (SUPERVISOR_DPSID)
	REFERENCES DM_EMPLOYEES (DPSID);

ALTER TABLE DM_ORGANIZATIONAL_UNITS ADD CONSTRAINT DM_OU_COMPANIES_FK FOREIGN KEY (COMPANY_NUMBER)
	REFERENCES DM_COMPANIES (COMPANY_NUMBER);

ALTER TABLE DM_EMPLOYEE_EVALUATIONS ADD CONSTRAINT DM_EE_EMP_FK FOREIGN KEY (DPSID)
	REFERENCES DM_EMPLOYEES (DPSID);

ALTER TABLE ORDERS_FLOW ADD CONSTRAINT CUSTOMERS_FK FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMERS_FLOW (ID);

ALTER TABLE DM_EMPLOYEES ADD CONSTRAINT DM_EMP_MGR_FK FOREIGN KEY (MANAGER_DPSID)
	REFERENCES DM_EMPLOYEES (DPSID);

ALTER TABLE DM_JOB_TYPES ADD CONSTRAINT DM_JT_FK_PARENT FOREIGN KEY (BIGGER_JOB_COMPANY, BIGGER_JOB_CODE)
	REFERENCES DM_JOB_TYPES (COMPANY_NUMBER, JOB_CODE);

ALTER TABLE DM_EMPLOYEE_EVALUATIONS ADD CONSTRAINT DM_EE_OU_FK FOREIGN KEY (COMPANY_NUMBER, OU_CODE)
	REFERENCES DM_ORGANIZATIONAL_UNITS (COMPANY_NUMBER, OU_CODE);

ALTER TABLE ORDERS_NF ADD CONSTRAINT CUSTOMERS_ORDERS_NF_FK FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMERS_NF (ID);

ALTER TABLE SUB_SALE_DIM ADD CONSTRAINT SUB_SALE_DIM_FK1 FOREIGN KEY (CATEGORY_ID)
	REFERENCES SUB_CATEGORY_DIM (CATEGORY_ID);

ALTER TABLE SUB_SALE_DIM ADD CONSTRAINT SUB_SALE_DIM_FK2 FOREIGN KEY (DEPT_ID)
	REFERENCES SUB_DEPT_DIM (DEPT_ID);

ALTER TABLE SUB_SALE_DIM ADD CONSTRAINT SUB_SALE_DIM_FK3 FOREIGN KEY (EMP_ID)
	REFERENCES SUB_EMP_DIM (EMP_ID);

ALTER TABLE SUB_SALE_DIM ADD CONSTRAINT SUB_SALE_DIM_FK4 FOREIGN KEY (EMP_SALARY_RANGE_ID)
	REFERENCES SUB_EMP_SALARY_RANGE_DIM (EMP_SALARY_RANGE_ID);

ALTER TABLE SUB_SALE_DIM ADD CONSTRAINT SUB_SALE_DIM_FK5 FOREIGN KEY (ITEM_ID)
	REFERENCES SUB_ITEM_DIM (ITEM_ID);

ALTER TABLE SUB_SALE_DIM ADD CONSTRAINT SUB_SALE_DIM_FK6 FOREIGN KEY (ITEM_PRICE_RANGE_ID)
	REFERENCES SUB_ITEM_PRICE_RANGE_DIM (ITEM_PRICE_RANGE_ID);

ALTER TABLE SUB_SALE_DIM ADD CONSTRAINT SUB_SALE_DIM_FK7 FOREIGN KEY (PROJECT_ID)
	REFERENCES SUB_PROJECT_DIM (PROJECT_ID);

ALTER TABLE SALE_DIM ADD CONSTRAINT EMP_DIM_FK FOREIGN KEY (EMP_ID) 
	REFERENCES EMP_DIM (EMP_ID);
	
ALTER TABLE SALE_DIM ADD CONSTRAINT DEPT_DIM_FK FOREIGN KEY (DEPT_ID) 
	REFERENCES DEPT_DIM (DEPT_ID);

ALTER TABLE SALE_DIM ADD CONSTRAINT CATEGORY_DIM_FK FOREIGN KEY (CATEGORY_ID) 
	REFERENCES CATEGORY_DIM (CATEGORY_ID);

ALTER TABLE SALE_DIM ADD CONSTRAINT EMP_SALARY_RANGE_DIM_FK FOREIGN KEY (EMP_SALARY_RANGE_ID) 
	REFERENCES EMP_SALARY_RANGE_DIM (EMP_SALARY_RANGE_ID);

ALTER TABLE SALE_DIM ADD CONSTRAINT ITEM_DIM_FK FOREIGN KEY (ITEM_ID) 
	REFERENCES ITEM_DIM (ITEM_ID);

ALTER TABLE SALE_DIM ADD CONSTRAINT ITEM_PRICE_RANGE_DIM_FK FOREIGN KEY (ITEM_PRICE_RANGE_ID) 
	REFERENCES ITEM_PRICE_RANGE_DIM (ITEM_PRICE_RANGE_ID);

ALTER TABLE SALE_DIM ADD CONSTRAINT PROJECT_DIM_FK FOREIGN KEY (PROJECT_ID) 
	REFERENCES PROJECT_DIM (PROJECT_ID);
