CREATE TABLE CUSTOMERS_OUT(
	SSN DECIMAL(9, 0) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL,
	FIRSTNAME VARCHAR(50),
	ADDRESS VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(2),
	ZIP VARCHAR(5)
);
