ALTER TABLE SCOTT.SALE_DIM DISABLE CONSTRAINT EMP_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM DISABLE CONSTRAINT DEPT_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM DISABLE CONSTRAINT CATEGORY_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM DISABLE CONSTRAINT EMP_SALARY_RANGE_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM DISABLE CONSTRAINT ITEM_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM DISABLE CONSTRAINT ITEM_PRICE_RANGE_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM DISABLE CONSTRAINT PROJECT_DIM_FK;
