ALTER TABLE SCOTT.SALE_DIM ENABLE CONSTRAINT EMP_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM ENABLE CONSTRAINT DEPT_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM ENABLE CONSTRAINT CATEGORY_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM ENABLE CONSTRAINT EMP_SALARY_RANGE_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM ENABLE CONSTRAINT ITEM_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM ENABLE CONSTRAINT ITEM_PRICE_RANGE_DIM_FK;
ALTER TABLE SCOTT.SALE_DIM ENABLE CONSTRAINT PROJECT_DIM_FK;
exit
