/INFILE=chiefs10.ascii
    /FIELD=(president,POS=1,SIZE=27)
    /FIELD=(term,POS=28,SIZE=9)
    /FIELD=(party,POS=40,SIZE=3)
    /FIELD=(state,POS=45,SIZE=2)
    
/REPORT

/OUTFILE=outfile
    /CHARSET=UTF16
    /ENDIAN=BOM,BIG
    /FIELD=(president,POS=1,SEP='|',UTF16_UNICODE)
    /FIELD=(term,POS=2,SEP='|',UTF16_UNICODE)
    /FIELD=(party,POS=3,SEP='|',UTF16_UNICODE)
    /FIELD=(state,POS=4,SEP='|',UTF16_UNICODE)
	