ALTER TABLE SCOTT.SAT_DV_JOBS_HR DROP CONSTRAINT SAT_DV_JOBS_HR_FK1;

ALTER TABLE SCOTT.LNK_DV_EMPLOYEES_HR_DV_EMPLOYEES_HR DROP CONSTRAINT LNK_DV_EMPLOYEES_HR_DV_EMPLOYEES_HR_FK1;

ALTER TABLE SCOTT.SAT_DV_COUNTRIES_HR DROP CONSTRAINT SAT_DV_COUNTRIES_HR_FK1;

ALTER TABLE SCOTT.LNK_DV_LOCATIONS_HR_DV_COUNTRIES_HR DROP CONSTRAINT LNK_DV_LOCATIONS_HR_DV_COUNTRIES_HR_FK1;

ALTER TABLE SCOTT.LNK_DV_DEPARTMENTS_HR_DV_LOCATIONS_HR DROP CONSTRAINT LNK_DV_DEPARTMENTS_HR_DV_LOCATIONS_HR_FK2;

ALTER TABLE SCOTT.SAT_DV_JOB_HISTORY_HR DROP CONSTRAINT SAT_DV_JOB_HISTORY_HR_FK1;

ALTER TABLE SCOTT.LNK_DV_JOB_HISTORY_HR_INFO DROP CONSTRAINT LNK_DV_JOB_HISTORY_HR_INFO_FK1;

ALTER TABLE SCOTT.LNK_DV_DEPARTMENTS_HR_DV_LOCATIONS_HR DROP CONSTRAINT LNK_DV_DEPARTMENTS_HR_DV_LOCATIONS_HR_FK1;

ALTER TABLE SCOTT.SAT_DV_DEPARTMENTS_HR DROP CONSTRAINT SAT_DV_DEPARTMENTS_HR_FK1;

ALTER TABLE SCOTT.SAT_DV_LOCATIONS_HR DROP CONSTRAINT SAT_DV_LOCATIONS_HR_FK1;

ALTER TABLE SCOTT.LNK_DV_COUNTRIES_HR_DV_REGIONS_HR DROP CONSTRAINT LNK_DV_COUNTRIES_HR_DV_REGIONS_HR_FK1;

ALTER TABLE SCOTT.LNK_DV_EMPLOYEES_HR_INFO DROP CONSTRAINT LNK_DV_EMPLOYEES_HR_INFO_FK2;

ALTER TABLE SCOTT.LNK_DV_JOB_HISTORY_HR_INFO DROP CONSTRAINT LNK_DV_JOB_HISTORY_HR_INFO_FK2;

ALTER TABLE SCOTT.SAT_DV_REGIONS_HR DROP CONSTRAINT SAT_DV_REGIONS_HR_FK1;

ALTER TABLE SCOTT.LNK_DV_EMPLOYEES_HR_INFO DROP CONSTRAINT LNK_DV_EMPLOYEES_HR_INFO_FK1;

ALTER TABLE SCOTT.LNK_DV_JOB_HISTORY_HR_INFO DROP CONSTRAINT LNK_DV_JOB_HISTORY_HR_INFO_FK3;

ALTER TABLE SCOTT.LNK_DV_EMPLOYEES_HR_INFO DROP CONSTRAINT LNK_DV_EMPLOYEES_HR_INFO_FK3;

ALTER TABLE SCOTT.LNK_DV_LOCATIONS_HR_DV_COUNTRIES_HR DROP CONSTRAINT LNK_DV_LOCATIONS_HR_DV_COUNTRIES_HR_FK2;

ALTER TABLE SCOTT.LNK_DV_JOB_HISTORY_HR_INFO DROP CONSTRAINT LNK_DV_JOB_HISTORY_HR_INFO_FK4;

ALTER TABLE SCOTT.LNK_DV_EMPLOYEES_HR_DV_EMPLOYEES_HR DROP CONSTRAINT LNK_DV_EMPLOYEES_HR_DV_EMPLOYEES_HR_FK2;

ALTER TABLE SCOTT.LNK_DV_COUNTRIES_HR_DV_REGIONS_HR DROP CONSTRAINT LNK_DV_COUNTRIES_HR_DV_REGIONS_HR_FK2;

ALTER TABLE SCOTT.SAT_DV_EMPLOYEES_HR DROP CONSTRAINT SAT_DV_EMPLOYEES_HR_FK1;

ALTER TABLE SCOTT.LNK_DV_EMPLOYEES_HR_INFO DROP CONSTRAINT LNK_DV_EMPLOYEES_HR_INFO_PK;

ALTER TABLE SCOTT.SAT_DV_JOB_HISTORY_HR DROP CONSTRAINT SAT_DV_JOB_HISTORY_HR_PK;

ALTER TABLE SCOTT.HUB_DV_COUNTRIES_HR DROP CONSTRAINT HUB_DV_COUNTRIES_HR_PK;

ALTER TABLE SCOTT.LNK_DV_LOCATIONS_HR_DV_COUNTRIES_HR DROP CONSTRAINT LNK_DV_LOCATIONS_HR_DV_COUNTRIES_HR_PK;

ALTER TABLE SCOTT.SAT_DV_REGIONS_HR DROP CONSTRAINT SAT_DV_REGIONS_HR_PK;

ALTER TABLE SCOTT.SAT_DV_EMPLOYEES_HR DROP CONSTRAINT SAT_DV_EMPLOYEES_HR_PK;

ALTER TABLE SCOTT.LNK_DV_JOB_HISTORY_HR_INFO DROP CONSTRAINT LNK_DV_JOB_HISTORY_HR_INFO_PK;

ALTER TABLE SCOTT.SAT_DV_LOCATIONS_HR DROP CONSTRAINT SAT_DV_LOCATIONS_HR_PK;

ALTER TABLE SCOTT.HUB_DV_REGIONS_HR DROP CONSTRAINT HUB_DV_REGIONS_HR_PK;

ALTER TABLE SCOTT.HUB_DV_EMPLOYEES_HR DROP CONSTRAINT HUB_DV_EMPLOYEES_HR_PK;

ALTER TABLE SCOTT.HUB_DV_DEPARTMENTS_HR DROP CONSTRAINT HUB_DV_DEPARTMENTS_HR_PK;

ALTER TABLE SCOTT.LNK_DV_EMPLOYEES_HR_DV_EMPLOYEES_HR DROP CONSTRAINT LNK_DV_EMPLOYEES_HR_DV_EMPLOYEES_HR_PK;

ALTER TABLE SCOTT.LNK_DV_DEPARTMENTS_HR_DV_LOCATIONS_HR DROP CONSTRAINT LNK_DV_DEPARTMENTS_HR_DV_LOCATIONS_HR_PK;

ALTER TABLE SCOTT.HUB_DV_JOB_HISTORY_HR DROP CONSTRAINT HUB_DV_JOB_HISTORY_HR_PK;

ALTER TABLE SCOTT.LNK_DV_COUNTRIES_HR_DV_REGIONS_HR DROP CONSTRAINT LNK_DV_COUNTRIES_HR_DV_REGIONS_HR_PK;

ALTER TABLE SCOTT.HUB_DV_JOBS_HR DROP CONSTRAINT HUB_DV_JOBS_HR_PK;

ALTER TABLE SCOTT.SAT_DV_COUNTRIES_HR DROP CONSTRAINT SAT_DV_COUNTRIES_HR_PK;

ALTER TABLE SCOTT.SAT_DV_JOBS_HR DROP CONSTRAINT SAT_DV_JOBS_HR_PK;

ALTER TABLE SCOTT.SAT_DV_DEPARTMENTS_HR DROP CONSTRAINT SAT_DV_DEPARTMENTS_HR_PK;

ALTER TABLE SCOTT.HUB_DV_LOCATIONS_HR DROP CONSTRAINT HUB_DV_LOCATIONS_HR_PK;

DROP INDEX SCOTT.LNK_DV_JOB_HISTORY_HR_INFO_IX;

DROP INDEX SCOTT.LNK_DV_EMPLOYEES_HR_INFO_IX;

DROP INDEX SCOTT.LNK_DV_DEPARTMENTS_HR_DV_LOCATIONS_HR_IX;

DROP INDEX SCOTT.HUB_DV_JOB_HISTORY_HR_IX;

DROP INDEX SCOTT.HUB_DV_REGIONS_HR_IX;

DROP INDEX SCOTT.LNK_DV_EMPLOYEES_HR_DV_EMPLOYEES_HR_IX;

DROP INDEX SCOTT.HUB_DV_LOCATIONS_HR_IX;

DROP INDEX SCOTT.LNK_DV_COUNTRIES_HR_DV_REGIONS_HR_IX;

DROP INDEX SCOTT.HUB_DV_COUNTRIES_HR_IX;

DROP INDEX SCOTT.HUB_DV_DEPARTMENTS_HR_IX;

DROP INDEX SCOTT.HUB_DV_EMPLOYEES_HR_IX;

DROP INDEX SCOTT.LNK_DV_LOCATIONS_HR_DV_COUNTRIES_HR_IX;

DROP INDEX SCOTT.HUB_DV_JOBS_HR_IX;

DROP TABLE SCOTT.LNK_DV_EMPLOYEES_HR_DV_EMPLOYEES_HR;

DROP TABLE SCOTT.HUB_DV_EMPLOYEES_HR;

DROP TABLE SCOTT.SAT_DV_LOCATIONS_HR;

DROP TABLE SCOTT.SAT_DV_JOB_HISTORY_HR;

DROP TABLE SCOTT.LNK_DV_COUNTRIES_HR_DV_REGIONS_HR;

DROP TABLE SCOTT.LNK_DV_LOCATIONS_HR_DV_COUNTRIES_HR;

DROP TABLE SCOTT.LNK_DV_EMPLOYEES_HR_INFO;

DROP TABLE SCOTT.HUB_DV_DEPARTMENTS_HR;

DROP TABLE SCOTT.SAT_DV_JOBS_HR;

DROP TABLE SCOTT.HUB_DV_JOB_HISTORY_HR;

DROP TABLE SCOTT.HUB_DV_COUNTRIES_HR;

DROP TABLE SCOTT.LNK_DV_JOB_HISTORY_HR_INFO;

DROP TABLE SCOTT.SAT_DV_EMPLOYEES_HR;

DROP TABLE SCOTT.HUB_DV_JOBS_HR;

DROP TABLE SCOTT.SAT_DV_REGIONS_HR;

DROP TABLE SCOTT.HUB_DV_LOCATIONS_HR;

DROP TABLE SCOTT.SAT_DV_DEPARTMENTS_HR;

DROP TABLE SCOTT.HUB_DV_REGIONS_HR;

DROP TABLE SCOTT.SAT_DV_COUNTRIES_HR;

DROP TABLE SCOTT.LNK_DV_DEPARTMENTS_HR_DV_LOCATIONS_HR;

