@echo off
SETLOCAL EnableDelayedExpansion
sqlplus scott/tiger@localhost:1521/XE < SCOTT.sql
sortcl /SPECIFICATION=Timestamp.scl
sqlplus scott/tiger@localhost:1521/XE < DisableFK_SCOTT.sql
sortcl /SPECIFICATION=JOB_ID_UNIQUE.rcl
sortcl /SPECIFICATION=REGION_ID_UNIQUE.rcl
sortcl /SPECIFICATION=COUNTRY_ID_UNIQUE.rcl
sortcl /SPECIFICATION=LOCATION_ID_UNIQUE.rcl
sortcl /SPECIFICATION=DEPARTMENT_ID_UNIQUE.rcl
sortcl /SPECIFICATION=EMPLOYEE_ID_UNIQUE.rcl
sortcl /SPECIFICATION=EMAIL_UNIQUE.rcl
sortcl /SPECIFICATION=START_DATE_UNIQUE.rcl
sortcl /SPECIFICATION=DV_JOBS_HR.rcl
sortcl /SPECIFICATION=DV_REGIONS_HR.rcl
sortcl /SPECIFICATION=DV_COUNTRIES_HR.rcl
sortcl /SPECIFICATION=DV_LOCATIONS_HR.rcl
sortcl /SPECIFICATION=DV_DEPARTMENTS_HR.rcl
sortcl /SPECIFICATION=DV_EMPLOYEES_HR.rcl
sortcl /SPECIFICATION=DV_JOB_HISTORY_HR.rcl
sortcl /SPECIFICATION=HUB_DV_REGIONS_HR_REGION_NAME.scl
sortcl /SPECIFICATION=HUB_DV_COUNTRIES_HR_COUNTRY_NAME.scl
sortcl /SPECIFICATION=HUB_DV_DEPARTMENTS_HR_DEPARTMENT_NAME.scl
sortcl /SPECIFICATION=HUB_DV_JOBS_HR_JOB_TITLE.scl
sortcl /SPECIFICATION=DV_JOBS_HR.scl
sortcl /SPECIFICATION=DV_REGIONS_HR.scl
sortcl /SPECIFICATION=DV_COUNTRIES_HR.scl
sortcl /SPECIFICATION=DV_LOCATIONS_HR.scl
sortcl /SPECIFICATION=DV_DEPARTMENTS_HR.scl
sortcl /SPECIFICATION=DV_EMPLOYEES_HR.scl
sortcl /SPECIFICATION=DV_JOB_HISTORY_HR.scl
sqlplus scott/tiger@localhost:1521/XE < EnableFK_SCOTT.sql
echo Job Ended