DROP TABLE PATIENT_RECORD_ENCRYPTED;

DROP TABLE PATIENT_RECORD;

CREATE TABLE PATIENT_RECORD_ENCRYPTED (
		IDNUMBER VARCHAR2(8),
		NAME VARCHAR2(50),
		AGE VARCHAR2(4),
		EMAIL VARCHAR2(50),
		PHONE VARCHAR2(30),
		CREDIT_CARD VARCHAR2(20),
		DRIVING_LICENSE VARCHAR2(30),
		SSN VARCHAR2(11),
		CITY VARCHAR2(20),
		STATE VARCHAR2(20)
	);

CREATE TABLE PATIENT_RECORD (
		IDNUMBER VARCHAR2(8),
		NAME VARCHAR2(50),
		AGE VARCHAR2(4),
		EMAIL VARCHAR2(50),
		PHONE VARCHAR2(30),
		CREDIT_CARD VARCHAR2(20),
		DRIVING_LICENSE VARCHAR2(30),
		SSN VARCHAR2(11),
		CITY VARCHAR2(20),
		STATE VARCHAR2(20)
	);

