
TRUNCATE TABLE DM_DCTA_EVALUATIONS;

ALTER TABLE DM_DCTA_EVALUATIONS DISABLE CONSTRAINT DM_EE_DCTAE_FK;
TRUNCATE TABLE DM_EMPLOYEE_EVALUATIONS;
ALTER TABLE DM_DCTA_EVALUATIONS ENABLE CONSTRAINT DM_EE_DCTAE_FK;

ALTER TABLE DM_EMPLOYEE_EVALUATIONS DISABLE CONSTRAINT DM_EE_OU_FK;
TRUNCATE TABLE DM_ORGANIZATIONAL_UNITS;
ALTER TABLE DM_EMPLOYEE_EVALUATIONS ENABLE CONSTRAINT DM_EE_OU_FK;

ALTER TABLE DM_EMPLOYEES DISABLE CONSTRAINT DM_EMP_EMP_FK;
ALTER TABLE DM_EMPLOYEES DISABLE CONSTRAINT DM_EMP_MGR_FK;
ALTER TABLE DM_EMPLOYEE_EVALUATIONS DISABLE CONSTRAINT DM_EE_EMP_FK;
TRUNCATE TABLE DM_EMPLOYEES;
--ALTER TABLE DM_EMPLOYEES ENABLE CONSTRAINT DM_EMP_EMP_FK;
--ALTER TABLE DM_EMPLOYEES ENABLE CONSTRAINT DM_EMP_MGR_FK;
ALTER TABLE DM_EMPLOYEE_EVALUATIONS ENABLE CONSTRAINT DM_EE_EMP_FK;

ALTER TABLE DM_JOB_TYPES DISABLE CONSTRAINT DM_JT_FK_PARENT_TOP;
ALTER TABLE DM_EMPLOYEE_EVALUATIONS DISABLE CONSTRAINT DM_EE_JT_FK;
ALTER TABLE DM_JOB_TYPES DISABLE CONSTRAINT DM_JT_FK_PARENT;
TRUNCATE TABLE DM_JOB_TYPES;
--ALTER TABLE DM_JOB_TYPES ENABLE CONSTRAINT DM_JT_FK_PARENT_TOP;
ALTER TABLE DM_EMPLOYEE_EVALUATIONS ENABLE CONSTRAINT DM_EE_JT_FK;
--ALTER TABLE DM_JOB_TYPES ENABLE CONSTRAINT DM_JT_FK_PARENT;

ALTER TABLE DM_ORGANIZATIONAL_UNITS DISABLE CONSTRAINT DM_OU_COMPANIES_FK;
ALTER TABLE DM_JOB_TYPES DISABLE CONSTRAINT DM_JT_COMPANIES_FK;
TRUNCATE TABLE DM_COMPANIES;
--ALTER TABLE DM_ORGANIZATIONAL_UNITS ENABLE CONSTRAINT DM_OU_COMPANIES_FK;
--ALTER TABLE DM_JOB_TYPES ENABLE CONSTRAINT DM_JT_COMPANIES_FK;
