CREATE TABLE JOB_HISTORY (
		EMPLOYEE_SID VARCHAR2(9) NOT NULL,
		START_DATE DATE NOT NULL,
		END_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE TABLE JOBS (
		JOB_ID VARCHAR2(10) NOT NULL,
		JOB_TITLE VARCHAR2(35) NOT NULL,
		MIN_SALARY NUMBER(6 , 0),
		MAX_SALARY NUMBER(6 , 0)
	);

CREATE TABLE EMPLOYEES (
		EMPLOYEE_SID VARCHAR2(9) NOT NULL,
		FIRST_NAME VARCHAR2(20),
		LAST_NAME VARCHAR2(25) NOT NULL,
		EMAIL VARCHAR2(25) NOT NULL,
		PHONE_NUMBER VARCHAR2(20),
		HIRE_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		SALARY NUMBER(8 , 2),
		COMMISSION_PCT NUMBER(3 , 2),
		MANAGER_SID VARCHAR2(9),
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE TABLE COUNTRIES (
		COUNTRY_ID CHAR(2) NOT NULL,
		COUNTRY_NAME VARCHAR2(40),
		REGION_ID NUMBER
	);

CREATE TABLE DEPARTMENTS (
		DEPARTMENT_ID NUMBER(4 , 0) NOT NULL,
		DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
		MANAGER_SID VARCHAR2(9),
		LOCATION_ID NUMBER(4 , 0)
	);

CREATE TABLE REGIONS (
		REGION_ID NUMBER NOT NULL,
		REGION_NAME VARCHAR2(25)
	);

CREATE TABLE LOCATIONS (
		LOCATION_ID NUMBER(4 , 0) NOT NULL,
		STREET_ADDRESS VARCHAR2(40),
		POSTAL_CODE VARCHAR2(12),
		CITY VARCHAR2(30) NOT NULL,
		STATE_PROVINCE VARCHAR2(25),
		COUNTRY_ID CHAR(2)
	);

CREATE INDEX DEPT_LOCATION_IX ON DEPARTMENTS (LOCATION_ID ASC);

CREATE UNIQUE INDEX EMP_EMP_ID_PK ON EMPLOYEES (EMPLOYEE_SID ASC);

CREATE UNIQUE INDEX LOC_ID_PK ON LOCATIONS (LOCATION_ID ASC);

CREATE INDEX LOC_COUNTRY_IX ON LOCATIONS (COUNTRY_ID ASC);

CREATE INDEX LOC_CITY_IX ON LOCATIONS (CITY ASC);

CREATE INDEX EMP_DEPARTMENT_IX ON EMPLOYEES (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX REG_ID_PK ON REGIONS (REGION_ID ASC);

CREATE INDEX EMP_NAME_IX ON EMPLOYEES (LAST_NAME ASC, FIRST_NAME ASC);

CREATE INDEX EMP_JOB_IX ON EMPLOYEES (JOB_ID ASC);

CREATE INDEX LOC_STATE_PROVINCE_IX ON LOCATIONS (STATE_PROVINCE ASC);

CREATE UNIQUE INDEX DEPT_ID_PK ON DEPARTMENTS (DEPARTMENT_ID ASC);

CREATE INDEX JHIST_JOB_IX ON JOB_HISTORY (JOB_ID ASC);

CREATE UNIQUE INDEX JHIST_EMP_ID_ST_DATE_PK ON JOB_HISTORY (EMPLOYEE_SID ASC, START_DATE ASC);

CREATE INDEX JHIST_DEPARTMENT_IX ON JOB_HISTORY (DEPARTMENT_ID ASC);

CREATE INDEX JHIST_EMPLOYEE_IX ON JOB_HISTORY (EMPLOYEE_SID ASC);

CREATE UNIQUE INDEX JOB_ID_PK ON JOBS (JOB_ID ASC);

CREATE INDEX EMP_MANAGER_IX ON EMPLOYEES (MANAGER_SID ASC);

CREATE UNIQUE INDEX EMP_EMAIL_UK ON EMPLOYEES (EMAIL ASC);

CREATE UNIQUE INDEX COUNTRY_C_ID_PK ON COUNTRIES (COUNTRY_ID ASC);

ALTER TABLE LOCATIONS ADD CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID);

ALTER TABLE JOBS ADD CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE REGIONS ADD CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_SID, START_DATE);

ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY (EMPLOYEE_SID);



ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRY_REG_FK FOREIGN KEY (REGION_ID)
	REFERENCES REGIONS(REGION_ID);

ALTER TABLE LOCATIONS ADD CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID)
	REFERENCES COUNTRIES(COUNTRY_ID);
        	  
ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID)
	REFERENCES LOCATIONS (LOCATION_ID);
        	  
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DEPARTMENTS;
	
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID)
	REFERENCES JOBS(JOB_ID);
	
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_MGNR_FK FOREIGN KEY (MANAGER_SID)
	REFERENCES EMPLOYEES;
	
ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPT_MGR_FK FOREIGN KEY (MANAGER_SID)
	REFERENCES EMPLOYEES (EMPLOYEE_SID);
	
ALTER TABLE JOB_HISTORY ADD CONSTRAINT JHIS_JOB_FK FOREIGN KEY (JOB_ID)
	REFERENCES JOBS;
	
ALTER TABLE JOB_HISTORY ADD CONSTRAINT JHIST_EMP_FK FOREIGN KEY (EMPLOYEE_SID)
	REFERENCES EMPLOYEES;

ALTER TABLE JOB_HISTORY ADD CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DEPARTMENTS;
	
	