ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_MGNR_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JHIST_EMP_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JHIS_JOB_FK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT DEPT_LOC_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_JOB_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JHIST_DEPT_FK;

ALTER TABLE LOCATIONS DROP CONSTRAINT LOC_C_ID_FK;

ALTER TABLE COUNTRIES DROP CONSTRAINT COUNTRY_REG_FK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT DEPT_MGR_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_DEPT_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JHIST_EMP_ID_ST_DATE_PK;

ALTER TABLE REGIONS DROP CONSTRAINT REG_ID_PK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_EMP_ID_PK;

ALTER TABLE LOCATIONS DROP CONSTRAINT LOC_ID_PK;

ALTER TABLE JOBS DROP CONSTRAINT JOB_ID_PK;

ALTER TABLE COUNTRIES DROP CONSTRAINT COUNTRY_C_ID_PK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT DEPT_ID_PK;

DROP INDEX JHIST_EMPLOYEE_IX;

DROP INDEX DEPT_LOCATION_IX;

DROP INDEX EMP_DEPARTMENT_IX;

DROP INDEX EMP_NAME_IX;

DROP INDEX JHIST_JOB_IX;

DROP INDEX LOC_COUNTRY_IX;

DROP INDEX JHIST_DEPARTMENT_IX;

DROP INDEX EMP_MANAGER_IX;

DROP INDEX EMP_JOB_IX;

DROP INDEX JHIST_EMP_ID_ST_DATE_PK;

DROP INDEX REG_ID_PK;

DROP INDEX COUNTRY_C_ID_PK;

DROP INDEX EMP_EMAIL_UK;

DROP INDEX EMP_EMP_ID_PK;

DROP INDEX LOC_STATE_PROVINCE_IX;

DROP INDEX LOC_CITY_IX;

DROP INDEX JOB_ID_PK;

DROP INDEX DEPT_ID_PK;

DROP INDEX LOC_ID_PK;

DROP TABLE LOCATIONS;

DROP TABLE COUNTRIES;

DROP TABLE JOB_HISTORY;

DROP TABLE JOBS;

DROP TABLE EMPLOYEES;

DROP TABLE REGIONS;

DROP TABLE DEPARTMENTS;
