ALTER TABLE LOCATIONS DROP CONSTRAINT L_C_ID_FK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT D_L_ID_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JH_J_ID_FK;

ALTER TABLE COUNTRIES DROP CONSTRAINT C_R_ID_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT E_D_ID_FK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT E_J_ID_FK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JH_D_ID_FK;

ALTER TABLE COUNTRIES DROP CONSTRAINT C_C_ID_PK;

ALTER TABLE DEPARTMENTS DROP CONSTRAINT D_D_ID_PK;

ALTER TABLE LOCATIONS DROP CONSTRAINT L_L_ID_PK;

ALTER TABLE JOB_HISTORY DROP CONSTRAINT JH_ID_PK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT E_ID_PK;

ALTER TABLE JOBS DROP CONSTRAINT J_J_ID_PK;

ALTER TABLE REGIONS DROP CONSTRAINT R_R_ID_PK;

DROP INDEX L_L_ID_PK;

DROP INDEX E_E_SID_UK;

DROP INDEX J_J_ID_PK;

DROP INDEX D_D_ID_PK;

DROP INDEX JH_E_SID_SD_UK;

DROP INDEX E_ID_PK;

DROP INDEX C_C_ID_PK;

DROP INDEX JH_ID_PK;

DROP INDEX R_R_ID_PK;

DROP TABLE DEPARTMENTS;

DROP TABLE LOCATIONS;

DROP TABLE COUNTRIES;

DROP TABLE EMPLOYEES;

DROP TABLE JOB_HISTORY;

DROP TABLE REGIONS;

DROP TABLE JOBS;

