LOAD DATA
INFILE 'C:\IRI\CoSort95\workbench\workspace\FACT_CoSort_Oracle_ETL\TargetFiles\table_output.dat'
TRUNCATE
INTO TABLE orders_sorted
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
	"ORDER_ID"	CHAR(4000), 
	"CUSTOMER"	CHAR(4000), 
	"EMPLOYEE"	CHAR(4000), 
	"SHIP_DATE"	TIMESTAMP	"SYYYYMMDDHH24MISS.FF6", 
	"FREIGHT"	INTEGER EXTERNAL
)

