ALTER TABLE ORDERS_NF DROP CONSTRAINT ORDERS_NF_ORDER_ID_PK;

ALTER TABLE CUSTOMERS_NF DROP CONSTRAINT CUSTOMERS_NF_ID_PK;

DROP INDEX ORDERS_NF_ORDER_ID_PK;

DROP INDEX CUSTOMERS_NF_ID_PK;

DROP TABLE ORDERS_NF;

DROP TABLE CUSTOMERS_NF;

CREATE TABLE CUSTOMERS_NF (
		ID NUMERIC(5, 0) NOT NULL,
		NAME VARCHAR(20) NOT NULL,
		ADDRESS VARCHAR(25),
		PHONE VARCHAR(10)
	);

CREATE UNIQUE INDEX CUSTOMERS_NF_ID_PK ON CUSTOMERS_NF (ID ASC);

ALTER TABLE CUSTOMERS_NF ADD CONSTRAINT CUSTOMERS_NF_ID_PK PRIMARY KEY (ID);

CREATE TABLE ORDERS_NF (
		ORDER_ID VARCHAR(5) NOT NULL,
		CUSTOMER_ID NUMERIC(5) NOT NULL,
		FREIGHT NUMERIC(5, 0),
		TOTAL NUMERIC(10, 2)
	);

CREATE UNIQUE INDEX ORDERS_NF_ORDER_ID_PK ON ORDERS_NF (ORDER_ID ASC);

ALTER TABLE ORDERS_NF ADD CONSTRAINT ORDERS_NF_ORDER_ID_PK PRIMARY KEY (ORDER_ID);

ALTER TABLE ORDERS_NF ADD CONSTRAINT CUSTOMERS_ORDERS_NF_FK FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMERS_NF (ID);